import * as _177 from "../confio/proofs";
export declare const ics23: {
    hashOpFromJSON(object: any): _177.HashOp;
    hashOpToJSON(object: _177.HashOp): string;
    lengthOpFromJSON(object: any): _177.LengthOp;
    lengthOpToJSON(object: _177.LengthOp): string;
    HashOp: typeof _177.HashOp;
    HashOpSDKType: typeof _177.HashOp;
    HashOpAmino: typeof _177.HashOp;
    LengthOp: typeof _177.LengthOp;
    LengthOpSDKType: typeof _177.LengthOp;
    LengthOpAmino: typeof _177.LengthOp;
    ExistenceProof: {
        typeUrl: string;
        encode(message: _177.ExistenceProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _177.ExistenceProof;
        fromPartial(object: Partial<_177.ExistenceProof>): _177.ExistenceProof;
        fromAmino(object: _177.ExistenceProofAmino): _177.ExistenceProof;
        toAmino(message: _177.ExistenceProof): _177.ExistenceProofAmino;
        fromAminoMsg(object: _177.ExistenceProofAminoMsg): _177.ExistenceProof;
        fromProtoMsg(message: _177.ExistenceProofProtoMsg): _177.ExistenceProof;
        toProto(message: _177.ExistenceProof): Uint8Array;
        toProtoMsg(message: _177.ExistenceProof): _177.ExistenceProofProtoMsg;
    };
    NonExistenceProof: {
        typeUrl: string;
        encode(message: _177.NonExistenceProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _177.NonExistenceProof;
        fromPartial(object: Partial<_177.NonExistenceProof>): _177.NonExistenceProof;
        fromAmino(object: _177.NonExistenceProofAmino): _177.NonExistenceProof;
        toAmino(message: _177.NonExistenceProof): _177.NonExistenceProofAmino;
        fromAminoMsg(object: _177.NonExistenceProofAminoMsg): _177.NonExistenceProof;
        fromProtoMsg(message: _177.NonExistenceProofProtoMsg): _177.NonExistenceProof;
        toProto(message: _177.NonExistenceProof): Uint8Array;
        toProtoMsg(message: _177.NonExistenceProof): _177.NonExistenceProofProtoMsg;
    };
    CommitmentProof: {
        typeUrl: string;
        encode(message: _177.CommitmentProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _177.CommitmentProof;
        fromPartial(object: Partial<_177.CommitmentProof>): _177.CommitmentProof;
        fromAmino(object: _177.CommitmentProofAmino): _177.CommitmentProof;
        toAmino(message: _177.CommitmentProof): _177.CommitmentProofAmino;
        fromAminoMsg(object: _177.CommitmentProofAminoMsg): _177.CommitmentProof;
        fromProtoMsg(message: _177.CommitmentProofProtoMsg): _177.CommitmentProof;
        toProto(message: _177.CommitmentProof): Uint8Array;
        toProtoMsg(message: _177.CommitmentProof): _177.CommitmentProofProtoMsg;
    };
    LeafOp: {
        typeUrl: string;
        encode(message: _177.LeafOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _177.LeafOp;
        fromPartial(object: Partial<_177.LeafOp>): _177.LeafOp;
        fromAmino(object: _177.LeafOpAmino): _177.LeafOp;
        toAmino(message: _177.LeafOp): _177.LeafOpAmino;
        fromAminoMsg(object: _177.LeafOpAminoMsg): _177.LeafOp;
        fromProtoMsg(message: _177.LeafOpProtoMsg): _177.LeafOp;
        toProto(message: _177.LeafOp): Uint8Array;
        toProtoMsg(message: _177.LeafOp): _177.LeafOpProtoMsg;
    };
    InnerOp: {
        typeUrl: string;
        encode(message: _177.InnerOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _177.InnerOp;
        fromPartial(object: Partial<_177.InnerOp>): _177.InnerOp;
        fromAmino(object: _177.InnerOpAmino): _177.InnerOp;
        toAmino(message: _177.InnerOp): _177.InnerOpAmino;
        fromAminoMsg(object: _177.InnerOpAminoMsg): _177.InnerOp;
        fromProtoMsg(message: _177.InnerOpProtoMsg): _177.InnerOp;
        toProto(message: _177.InnerOp): Uint8Array;
        toProtoMsg(message: _177.InnerOp): _177.InnerOpProtoMsg;
    };
    ProofSpec: {
        typeUrl: string;
        encode(message: _177.ProofSpec, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _177.ProofSpec;
        fromPartial(object: Partial<_177.ProofSpec>): _177.ProofSpec;
        fromAmino(object: _177.ProofSpecAmino): _177.ProofSpec;
        toAmino(message: _177.ProofSpec): _177.ProofSpecAmino;
        fromAminoMsg(object: _177.ProofSpecAminoMsg): _177.ProofSpec;
        fromProtoMsg(message: _177.ProofSpecProtoMsg): _177.ProofSpec;
        toProto(message: _177.ProofSpec): Uint8Array;
        toProtoMsg(message: _177.ProofSpec): _177.ProofSpecProtoMsg;
    };
    InnerSpec: {
        typeUrl: string;
        encode(message: _177.InnerSpec, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _177.InnerSpec;
        fromPartial(object: Partial<_177.InnerSpec>): _177.InnerSpec;
        fromAmino(object: _177.InnerSpecAmino): _177.InnerSpec;
        toAmino(message: _177.InnerSpec): _177.InnerSpecAmino;
        fromAminoMsg(object: _177.InnerSpecAminoMsg): _177.InnerSpec;
        fromProtoMsg(message: _177.InnerSpecProtoMsg): _177.InnerSpec;
        toProto(message: _177.InnerSpec): Uint8Array;
        toProtoMsg(message: _177.InnerSpec): _177.InnerSpecProtoMsg;
    };
    BatchProof: {
        typeUrl: string;
        encode(message: _177.BatchProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _177.BatchProof;
        fromPartial(object: Partial<_177.BatchProof>): _177.BatchProof;
        fromAmino(object: _177.BatchProofAmino): _177.BatchProof;
        toAmino(message: _177.BatchProof): _177.BatchProofAmino;
        fromAminoMsg(object: _177.BatchProofAminoMsg): _177.BatchProof;
        fromProtoMsg(message: _177.BatchProofProtoMsg): _177.BatchProof;
        toProto(message: _177.BatchProof): Uint8Array;
        toProtoMsg(message: _177.BatchProof): _177.BatchProofProtoMsg;
    };
    BatchEntry: {
        typeUrl: string;
        encode(message: _177.BatchEntry, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _177.BatchEntry;
        fromPartial(object: Partial<_177.BatchEntry>): _177.BatchEntry;
        fromAmino(object: _177.BatchEntryAmino): _177.BatchEntry;
        toAmino(message: _177.BatchEntry): _177.BatchEntryAmino;
        fromAminoMsg(object: _177.BatchEntryAminoMsg): _177.BatchEntry;
        fromProtoMsg(message: _177.BatchEntryProtoMsg): _177.BatchEntry;
        toProto(message: _177.BatchEntry): Uint8Array;
        toProtoMsg(message: _177.BatchEntry): _177.BatchEntryProtoMsg;
    };
    CompressedBatchProof: {
        typeUrl: string;
        encode(message: _177.CompressedBatchProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _177.CompressedBatchProof;
        fromPartial(object: Partial<_177.CompressedBatchProof>): _177.CompressedBatchProof;
        fromAmino(object: _177.CompressedBatchProofAmino): _177.CompressedBatchProof;
        toAmino(message: _177.CompressedBatchProof): _177.CompressedBatchProofAmino;
        fromAminoMsg(object: _177.CompressedBatchProofAminoMsg): _177.CompressedBatchProof;
        fromProtoMsg(message: _177.CompressedBatchProofProtoMsg): _177.CompressedBatchProof;
        toProto(message: _177.CompressedBatchProof): Uint8Array;
        toProtoMsg(message: _177.CompressedBatchProof): _177.CompressedBatchProofProtoMsg;
    };
    CompressedBatchEntry: {
        typeUrl: string;
        encode(message: _177.CompressedBatchEntry, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _177.CompressedBatchEntry;
        fromPartial(object: Partial<_177.CompressedBatchEntry>): _177.CompressedBatchEntry;
        fromAmino(object: _177.CompressedBatchEntryAmino): _177.CompressedBatchEntry;
        toAmino(message: _177.CompressedBatchEntry): _177.CompressedBatchEntryAmino;
        fromAminoMsg(object: _177.CompressedBatchEntryAminoMsg): _177.CompressedBatchEntry;
        fromProtoMsg(message: _177.CompressedBatchEntryProtoMsg): _177.CompressedBatchEntry;
        toProto(message: _177.CompressedBatchEntry): Uint8Array;
        toProtoMsg(message: _177.CompressedBatchEntry): _177.CompressedBatchEntryProtoMsg;
    };
    CompressedExistenceProof: {
        typeUrl: string;
        encode(message: _177.CompressedExistenceProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _177.CompressedExistenceProof;
        fromPartial(object: Partial<_177.CompressedExistenceProof>): _177.CompressedExistenceProof;
        fromAmino(object: _177.CompressedExistenceProofAmino): _177.CompressedExistenceProof;
        toAmino(message: _177.CompressedExistenceProof): _177.CompressedExistenceProofAmino;
        fromAminoMsg(object: _177.CompressedExistenceProofAminoMsg): _177.CompressedExistenceProof;
        fromProtoMsg(message: _177.CompressedExistenceProofProtoMsg): _177.CompressedExistenceProof;
        toProto(message: _177.CompressedExistenceProof): Uint8Array;
        toProtoMsg(message: _177.CompressedExistenceProof): _177.CompressedExistenceProofProtoMsg;
    };
    CompressedNonExistenceProof: {
        typeUrl: string;
        encode(message: _177.CompressedNonExistenceProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _177.CompressedNonExistenceProof;
        fromPartial(object: Partial<_177.CompressedNonExistenceProof>): _177.CompressedNonExistenceProof;
        fromAmino(object: _177.CompressedNonExistenceProofAmino): _177.CompressedNonExistenceProof;
        toAmino(message: _177.CompressedNonExistenceProof): _177.CompressedNonExistenceProofAmino;
        fromAminoMsg(object: _177.CompressedNonExistenceProofAminoMsg): _177.CompressedNonExistenceProof;
        fromProtoMsg(message: _177.CompressedNonExistenceProofProtoMsg): _177.CompressedNonExistenceProof;
        toProto(message: _177.CompressedNonExistenceProof): Uint8Array;
        toProtoMsg(message: _177.CompressedNonExistenceProof): _177.CompressedNonExistenceProofProtoMsg;
    };
};
