import * as _1 from "../confio/proofs";
export declare const ics23: {
    hashOpFromJSON(object: any): _1.HashOp;
    hashOpToJSON(object: _1.HashOp): string;
    lengthOpFromJSON(object: any): _1.LengthOp;
    lengthOpToJSON(object: _1.LengthOp): string;
    HashOp: typeof _1.HashOp;
    HashOpSDKType: typeof _1.HashOp;
    HashOpAmino: typeof _1.HashOp;
    LengthOp: typeof _1.LengthOp;
    LengthOpSDKType: typeof _1.LengthOp;
    LengthOpAmino: typeof _1.LengthOp;
    ExistenceProof: {
        encode(message: _1.ExistenceProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _1.ExistenceProof;
        fromPartial(object: Partial<_1.ExistenceProof>): _1.ExistenceProof;
        fromAmino(object: _1.ExistenceProofAmino): _1.ExistenceProof;
        toAmino(message: _1.ExistenceProof): _1.ExistenceProofAmino;
        fromAminoMsg(object: _1.ExistenceProofAminoMsg): _1.ExistenceProof;
        fromProtoMsg(message: _1.ExistenceProofProtoMsg): _1.ExistenceProof;
        toProto(message: _1.ExistenceProof): Uint8Array;
        toProtoMsg(message: _1.ExistenceProof): _1.ExistenceProofProtoMsg;
    };
    NonExistenceProof: {
        encode(message: _1.NonExistenceProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _1.NonExistenceProof;
        fromPartial(object: Partial<_1.NonExistenceProof>): _1.NonExistenceProof;
        fromAmino(object: _1.NonExistenceProofAmino): _1.NonExistenceProof;
        toAmino(message: _1.NonExistenceProof): _1.NonExistenceProofAmino;
        fromAminoMsg(object: _1.NonExistenceProofAminoMsg): _1.NonExistenceProof;
        fromProtoMsg(message: _1.NonExistenceProofProtoMsg): _1.NonExistenceProof;
        toProto(message: _1.NonExistenceProof): Uint8Array;
        toProtoMsg(message: _1.NonExistenceProof): _1.NonExistenceProofProtoMsg;
    };
    CommitmentProof: {
        encode(message: _1.CommitmentProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _1.CommitmentProof;
        fromPartial(object: Partial<_1.CommitmentProof>): _1.CommitmentProof;
        fromAmino(object: _1.CommitmentProofAmino): _1.CommitmentProof;
        toAmino(message: _1.CommitmentProof): _1.CommitmentProofAmino;
        fromAminoMsg(object: _1.CommitmentProofAminoMsg): _1.CommitmentProof;
        fromProtoMsg(message: _1.CommitmentProofProtoMsg): _1.CommitmentProof;
        toProto(message: _1.CommitmentProof): Uint8Array;
        toProtoMsg(message: _1.CommitmentProof): _1.CommitmentProofProtoMsg;
    };
    LeafOp: {
        encode(message: _1.LeafOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _1.LeafOp;
        fromPartial(object: Partial<_1.LeafOp>): _1.LeafOp;
        fromAmino(object: _1.LeafOpAmino): _1.LeafOp;
        toAmino(message: _1.LeafOp): _1.LeafOpAmino;
        fromAminoMsg(object: _1.LeafOpAminoMsg): _1.LeafOp;
        fromProtoMsg(message: _1.LeafOpProtoMsg): _1.LeafOp;
        toProto(message: _1.LeafOp): Uint8Array;
        toProtoMsg(message: _1.LeafOp): _1.LeafOpProtoMsg;
    };
    InnerOp: {
        encode(message: _1.InnerOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _1.InnerOp;
        fromPartial(object: Partial<_1.InnerOp>): _1.InnerOp;
        fromAmino(object: _1.InnerOpAmino): _1.InnerOp;
        toAmino(message: _1.InnerOp): _1.InnerOpAmino;
        fromAminoMsg(object: _1.InnerOpAminoMsg): _1.InnerOp;
        fromProtoMsg(message: _1.InnerOpProtoMsg): _1.InnerOp;
        toProto(message: _1.InnerOp): Uint8Array;
        toProtoMsg(message: _1.InnerOp): _1.InnerOpProtoMsg;
    };
    ProofSpec: {
        encode(message: _1.ProofSpec, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _1.ProofSpec;
        fromPartial(object: Partial<_1.ProofSpec>): _1.ProofSpec;
        fromAmino(object: _1.ProofSpecAmino): _1.ProofSpec;
        toAmino(message: _1.ProofSpec): _1.ProofSpecAmino;
        fromAminoMsg(object: _1.ProofSpecAminoMsg): _1.ProofSpec;
        fromProtoMsg(message: _1.ProofSpecProtoMsg): _1.ProofSpec;
        toProto(message: _1.ProofSpec): Uint8Array;
        toProtoMsg(message: _1.ProofSpec): _1.ProofSpecProtoMsg;
    };
    InnerSpec: {
        encode(message: _1.InnerSpec, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _1.InnerSpec;
        fromPartial(object: Partial<_1.InnerSpec>): _1.InnerSpec;
        fromAmino(object: _1.InnerSpecAmino): _1.InnerSpec;
        toAmino(message: _1.InnerSpec): _1.InnerSpecAmino;
        fromAminoMsg(object: _1.InnerSpecAminoMsg): _1.InnerSpec;
        fromProtoMsg(message: _1.InnerSpecProtoMsg): _1.InnerSpec;
        toProto(message: _1.InnerSpec): Uint8Array;
        toProtoMsg(message: _1.InnerSpec): _1.InnerSpecProtoMsg;
    };
    BatchProof: {
        encode(message: _1.BatchProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _1.BatchProof;
        fromPartial(object: Partial<_1.BatchProof>): _1.BatchProof;
        fromAmino(object: _1.BatchProofAmino): _1.BatchProof;
        toAmino(message: _1.BatchProof): _1.BatchProofAmino;
        fromAminoMsg(object: _1.BatchProofAminoMsg): _1.BatchProof;
        fromProtoMsg(message: _1.BatchProofProtoMsg): _1.BatchProof;
        toProto(message: _1.BatchProof): Uint8Array;
        toProtoMsg(message: _1.BatchProof): _1.BatchProofProtoMsg;
    };
    BatchEntry: {
        encode(message: _1.BatchEntry, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _1.BatchEntry;
        fromPartial(object: Partial<_1.BatchEntry>): _1.BatchEntry;
        fromAmino(object: _1.BatchEntryAmino): _1.BatchEntry;
        toAmino(message: _1.BatchEntry): _1.BatchEntryAmino;
        fromAminoMsg(object: _1.BatchEntryAminoMsg): _1.BatchEntry;
        fromProtoMsg(message: _1.BatchEntryProtoMsg): _1.BatchEntry;
        toProto(message: _1.BatchEntry): Uint8Array;
        toProtoMsg(message: _1.BatchEntry): _1.BatchEntryProtoMsg;
    };
    CompressedBatchProof: {
        encode(message: _1.CompressedBatchProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _1.CompressedBatchProof;
        fromPartial(object: Partial<_1.CompressedBatchProof>): _1.CompressedBatchProof;
        fromAmino(object: _1.CompressedBatchProofAmino): _1.CompressedBatchProof;
        toAmino(message: _1.CompressedBatchProof): _1.CompressedBatchProofAmino;
        fromAminoMsg(object: _1.CompressedBatchProofAminoMsg): _1.CompressedBatchProof;
        fromProtoMsg(message: _1.CompressedBatchProofProtoMsg): _1.CompressedBatchProof;
        toProto(message: _1.CompressedBatchProof): Uint8Array;
        toProtoMsg(message: _1.CompressedBatchProof): _1.CompressedBatchProofProtoMsg;
    };
    CompressedBatchEntry: {
        encode(message: _1.CompressedBatchEntry, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _1.CompressedBatchEntry;
        fromPartial(object: Partial<_1.CompressedBatchEntry>): _1.CompressedBatchEntry;
        fromAmino(object: _1.CompressedBatchEntryAmino): _1.CompressedBatchEntry;
        toAmino(message: _1.CompressedBatchEntry): _1.CompressedBatchEntryAmino;
        fromAminoMsg(object: _1.CompressedBatchEntryAminoMsg): _1.CompressedBatchEntry;
        fromProtoMsg(message: _1.CompressedBatchEntryProtoMsg): _1.CompressedBatchEntry;
        toProto(message: _1.CompressedBatchEntry): Uint8Array;
        toProtoMsg(message: _1.CompressedBatchEntry): _1.CompressedBatchEntryProtoMsg;
    };
    CompressedExistenceProof: {
        encode(message: _1.CompressedExistenceProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _1.CompressedExistenceProof;
        fromPartial(object: Partial<_1.CompressedExistenceProof>): _1.CompressedExistenceProof;
        fromAmino(object: _1.CompressedExistenceProofAmino): _1.CompressedExistenceProof;
        toAmino(message: _1.CompressedExistenceProof): _1.CompressedExistenceProofAmino;
        fromAminoMsg(object: _1.CompressedExistenceProofAminoMsg): _1.CompressedExistenceProof;
        fromProtoMsg(message: _1.CompressedExistenceProofProtoMsg): _1.CompressedExistenceProof;
        toProto(message: _1.CompressedExistenceProof): Uint8Array;
        toProtoMsg(message: _1.CompressedExistenceProof): _1.CompressedExistenceProofProtoMsg;
    };
    CompressedNonExistenceProof: {
        encode(message: _1.CompressedNonExistenceProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _1.CompressedNonExistenceProof;
        fromPartial(object: Partial<_1.CompressedNonExistenceProof>): _1.CompressedNonExistenceProof;
        fromAmino(object: _1.CompressedNonExistenceProofAmino): _1.CompressedNonExistenceProof;
        toAmino(message: _1.CompressedNonExistenceProof): _1.CompressedNonExistenceProofAmino;
        fromAminoMsg(object: _1.CompressedNonExistenceProofAminoMsg): _1.CompressedNonExistenceProof;
        fromProtoMsg(message: _1.CompressedNonExistenceProofProtoMsg): _1.CompressedNonExistenceProof;
        toProto(message: _1.CompressedNonExistenceProof): Uint8Array;
        toProtoMsg(message: _1.CompressedNonExistenceProof): _1.CompressedNonExistenceProofProtoMsg;
    };
};
