import * as _183 from "./protobuf/any";
import * as _184 from "./protobuf/descriptor";
import * as _185 from "./protobuf/duration";
import * as _186 from "./protobuf/empty";
import * as _187 from "./protobuf/timestamp";
export declare namespace google {
    const protobuf: {
        Timestamp: {
            typeUrl: string;
            encode(message: _187.Timestamp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _187.Timestamp;
            fromPartial(object: Partial<_187.Timestamp>): _187.Timestamp;
            fromAmino(object: string): _187.Timestamp;
            toAmino(message: _187.Timestamp): string;
            fromAminoMsg(object: _187.TimestampAminoMsg): _187.Timestamp;
            fromProtoMsg(message: _187.TimestampProtoMsg): _187.Timestamp;
            toProto(message: _187.Timestamp): Uint8Array;
            toProtoMsg(message: _187.Timestamp): _187.TimestampProtoMsg;
        };
        Empty: {
            typeUrl: string;
            encode(_: _186.Empty, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _186.Empty;
            fromPartial(_: Partial<_186.Empty>): _186.Empty;
            fromAmino(_: _186.EmptyAmino): _186.Empty;
            toAmino(_: _186.Empty): _186.EmptyAmino;
            fromAminoMsg(object: _186.EmptyAminoMsg): _186.Empty;
            fromProtoMsg(message: _186.EmptyProtoMsg): _186.Empty;
            toProto(message: _186.Empty): Uint8Array;
            toProtoMsg(message: _186.Empty): _186.EmptyProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _185.Duration, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _185.Duration;
            fromPartial(object: Partial<_185.Duration>): _185.Duration;
            fromAmino(object: string): _185.Duration;
            toAmino(message: _185.Duration): string;
            fromAminoMsg(object: _185.DurationAminoMsg): _185.Duration;
            fromProtoMsg(message: _185.DurationProtoMsg): _185.Duration;
            toProto(message: _185.Duration): Uint8Array;
            toProtoMsg(message: _185.Duration): _185.DurationProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _184.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _184.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _184.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _184.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _184.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _184.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _184.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _184.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _184.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _184.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _184.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _184.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _184.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _184.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _184.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _184.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _184.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _184.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _184.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _184.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _184.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _184.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _184.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _184.FieldOptions_CType;
        FieldOptions_JSType: typeof _184.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _184.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _184.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _184.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _184.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _184.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _184.FileDescriptorSet, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.FileDescriptorSet;
            fromPartial(object: Partial<_184.FileDescriptorSet>): _184.FileDescriptorSet;
            fromAmino(object: _184.FileDescriptorSetAmino): _184.FileDescriptorSet;
            toAmino(message: _184.FileDescriptorSet): _184.FileDescriptorSetAmino;
            fromAminoMsg(object: _184.FileDescriptorSetAminoMsg): _184.FileDescriptorSet;
            fromProtoMsg(message: _184.FileDescriptorSetProtoMsg): _184.FileDescriptorSet;
            toProto(message: _184.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _184.FileDescriptorSet): _184.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _184.FileDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.FileDescriptorProto;
            fromPartial(object: Partial<_184.FileDescriptorProto>): _184.FileDescriptorProto;
            fromAmino(object: _184.FileDescriptorProtoAmino): _184.FileDescriptorProto;
            toAmino(message: _184.FileDescriptorProto): _184.FileDescriptorProtoAmino;
            fromAminoMsg(object: _184.FileDescriptorProtoAminoMsg): _184.FileDescriptorProto;
            fromProtoMsg(message: _184.FileDescriptorProtoProtoMsg): _184.FileDescriptorProto;
            toProto(message: _184.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _184.FileDescriptorProto): _184.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _184.DescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.DescriptorProto;
            fromPartial(object: Partial<_184.DescriptorProto>): _184.DescriptorProto;
            fromAmino(object: _184.DescriptorProtoAmino): _184.DescriptorProto;
            toAmino(message: _184.DescriptorProto): _184.DescriptorProtoAmino;
            fromAminoMsg(object: _184.DescriptorProtoAminoMsg): _184.DescriptorProto;
            fromProtoMsg(message: _184.DescriptorProtoProtoMsg): _184.DescriptorProto;
            toProto(message: _184.DescriptorProto): Uint8Array;
            toProtoMsg(message: _184.DescriptorProto): _184.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _184.DescriptorProto_ExtensionRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_184.DescriptorProto_ExtensionRange>): _184.DescriptorProto_ExtensionRange;
            fromAmino(object: _184.DescriptorProto_ExtensionRangeAmino): _184.DescriptorProto_ExtensionRange;
            toAmino(message: _184.DescriptorProto_ExtensionRange): _184.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _184.DescriptorProto_ExtensionRangeAminoMsg): _184.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _184.DescriptorProto_ExtensionRangeProtoMsg): _184.DescriptorProto_ExtensionRange;
            toProto(message: _184.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _184.DescriptorProto_ExtensionRange): _184.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _184.DescriptorProto_ReservedRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_184.DescriptorProto_ReservedRange>): _184.DescriptorProto_ReservedRange;
            fromAmino(object: _184.DescriptorProto_ReservedRangeAmino): _184.DescriptorProto_ReservedRange;
            toAmino(message: _184.DescriptorProto_ReservedRange): _184.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _184.DescriptorProto_ReservedRangeAminoMsg): _184.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _184.DescriptorProto_ReservedRangeProtoMsg): _184.DescriptorProto_ReservedRange;
            toProto(message: _184.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _184.DescriptorProto_ReservedRange): _184.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _184.ExtensionRangeOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.ExtensionRangeOptions;
            fromPartial(object: Partial<_184.ExtensionRangeOptions>): _184.ExtensionRangeOptions;
            fromAmino(object: _184.ExtensionRangeOptionsAmino): _184.ExtensionRangeOptions;
            toAmino(message: _184.ExtensionRangeOptions): _184.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _184.ExtensionRangeOptionsAminoMsg): _184.ExtensionRangeOptions;
            fromProtoMsg(message: _184.ExtensionRangeOptionsProtoMsg): _184.ExtensionRangeOptions;
            toProto(message: _184.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _184.ExtensionRangeOptions): _184.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _184.FieldDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.FieldDescriptorProto;
            fromPartial(object: Partial<_184.FieldDescriptorProto>): _184.FieldDescriptorProto;
            fromAmino(object: _184.FieldDescriptorProtoAmino): _184.FieldDescriptorProto;
            toAmino(message: _184.FieldDescriptorProto): _184.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _184.FieldDescriptorProtoAminoMsg): _184.FieldDescriptorProto;
            fromProtoMsg(message: _184.FieldDescriptorProtoProtoMsg): _184.FieldDescriptorProto;
            toProto(message: _184.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _184.FieldDescriptorProto): _184.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _184.OneofDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.OneofDescriptorProto;
            fromPartial(object: Partial<_184.OneofDescriptorProto>): _184.OneofDescriptorProto;
            fromAmino(object: _184.OneofDescriptorProtoAmino): _184.OneofDescriptorProto;
            toAmino(message: _184.OneofDescriptorProto): _184.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _184.OneofDescriptorProtoAminoMsg): _184.OneofDescriptorProto;
            fromProtoMsg(message: _184.OneofDescriptorProtoProtoMsg): _184.OneofDescriptorProto;
            toProto(message: _184.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _184.OneofDescriptorProto): _184.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _184.EnumDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.EnumDescriptorProto;
            fromPartial(object: Partial<_184.EnumDescriptorProto>): _184.EnumDescriptorProto;
            fromAmino(object: _184.EnumDescriptorProtoAmino): _184.EnumDescriptorProto;
            toAmino(message: _184.EnumDescriptorProto): _184.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _184.EnumDescriptorProtoAminoMsg): _184.EnumDescriptorProto;
            fromProtoMsg(message: _184.EnumDescriptorProtoProtoMsg): _184.EnumDescriptorProto;
            toProto(message: _184.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _184.EnumDescriptorProto): _184.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _184.EnumDescriptorProto_EnumReservedRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_184.EnumDescriptorProto_EnumReservedRange>): _184.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _184.EnumDescriptorProto_EnumReservedRangeAmino): _184.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _184.EnumDescriptorProto_EnumReservedRange): _184.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _184.EnumDescriptorProto_EnumReservedRangeAminoMsg): _184.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _184.EnumDescriptorProto_EnumReservedRangeProtoMsg): _184.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _184.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _184.EnumDescriptorProto_EnumReservedRange): _184.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _184.EnumValueDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.EnumValueDescriptorProto;
            fromPartial(object: Partial<_184.EnumValueDescriptorProto>): _184.EnumValueDescriptorProto;
            fromAmino(object: _184.EnumValueDescriptorProtoAmino): _184.EnumValueDescriptorProto;
            toAmino(message: _184.EnumValueDescriptorProto): _184.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _184.EnumValueDescriptorProtoAminoMsg): _184.EnumValueDescriptorProto;
            fromProtoMsg(message: _184.EnumValueDescriptorProtoProtoMsg): _184.EnumValueDescriptorProto;
            toProto(message: _184.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _184.EnumValueDescriptorProto): _184.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _184.ServiceDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.ServiceDescriptorProto;
            fromPartial(object: Partial<_184.ServiceDescriptorProto>): _184.ServiceDescriptorProto;
            fromAmino(object: _184.ServiceDescriptorProtoAmino): _184.ServiceDescriptorProto;
            toAmino(message: _184.ServiceDescriptorProto): _184.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _184.ServiceDescriptorProtoAminoMsg): _184.ServiceDescriptorProto;
            fromProtoMsg(message: _184.ServiceDescriptorProtoProtoMsg): _184.ServiceDescriptorProto;
            toProto(message: _184.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _184.ServiceDescriptorProto): _184.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _184.MethodDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.MethodDescriptorProto;
            fromPartial(object: Partial<_184.MethodDescriptorProto>): _184.MethodDescriptorProto;
            fromAmino(object: _184.MethodDescriptorProtoAmino): _184.MethodDescriptorProto;
            toAmino(message: _184.MethodDescriptorProto): _184.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _184.MethodDescriptorProtoAminoMsg): _184.MethodDescriptorProto;
            fromProtoMsg(message: _184.MethodDescriptorProtoProtoMsg): _184.MethodDescriptorProto;
            toProto(message: _184.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _184.MethodDescriptorProto): _184.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _184.FileOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.FileOptions;
            fromPartial(object: Partial<_184.FileOptions>): _184.FileOptions;
            fromAmino(object: _184.FileOptionsAmino): _184.FileOptions;
            toAmino(message: _184.FileOptions): _184.FileOptionsAmino;
            fromAminoMsg(object: _184.FileOptionsAminoMsg): _184.FileOptions;
            fromProtoMsg(message: _184.FileOptionsProtoMsg): _184.FileOptions;
            toProto(message: _184.FileOptions): Uint8Array;
            toProtoMsg(message: _184.FileOptions): _184.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _184.MessageOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.MessageOptions;
            fromPartial(object: Partial<_184.MessageOptions>): _184.MessageOptions;
            fromAmino(object: _184.MessageOptionsAmino): _184.MessageOptions;
            toAmino(message: _184.MessageOptions): _184.MessageOptionsAmino;
            fromAminoMsg(object: _184.MessageOptionsAminoMsg): _184.MessageOptions;
            fromProtoMsg(message: _184.MessageOptionsProtoMsg): _184.MessageOptions;
            toProto(message: _184.MessageOptions): Uint8Array;
            toProtoMsg(message: _184.MessageOptions): _184.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _184.FieldOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.FieldOptions;
            fromPartial(object: Partial<_184.FieldOptions>): _184.FieldOptions;
            fromAmino(object: _184.FieldOptionsAmino): _184.FieldOptions;
            toAmino(message: _184.FieldOptions): _184.FieldOptionsAmino;
            fromAminoMsg(object: _184.FieldOptionsAminoMsg): _184.FieldOptions;
            fromProtoMsg(message: _184.FieldOptionsProtoMsg): _184.FieldOptions;
            toProto(message: _184.FieldOptions): Uint8Array;
            toProtoMsg(message: _184.FieldOptions): _184.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _184.OneofOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.OneofOptions;
            fromPartial(object: Partial<_184.OneofOptions>): _184.OneofOptions;
            fromAmino(object: _184.OneofOptionsAmino): _184.OneofOptions;
            toAmino(message: _184.OneofOptions): _184.OneofOptionsAmino;
            fromAminoMsg(object: _184.OneofOptionsAminoMsg): _184.OneofOptions;
            fromProtoMsg(message: _184.OneofOptionsProtoMsg): _184.OneofOptions;
            toProto(message: _184.OneofOptions): Uint8Array;
            toProtoMsg(message: _184.OneofOptions): _184.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _184.EnumOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.EnumOptions;
            fromPartial(object: Partial<_184.EnumOptions>): _184.EnumOptions;
            fromAmino(object: _184.EnumOptionsAmino): _184.EnumOptions;
            toAmino(message: _184.EnumOptions): _184.EnumOptionsAmino;
            fromAminoMsg(object: _184.EnumOptionsAminoMsg): _184.EnumOptions;
            fromProtoMsg(message: _184.EnumOptionsProtoMsg): _184.EnumOptions;
            toProto(message: _184.EnumOptions): Uint8Array;
            toProtoMsg(message: _184.EnumOptions): _184.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _184.EnumValueOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.EnumValueOptions;
            fromPartial(object: Partial<_184.EnumValueOptions>): _184.EnumValueOptions;
            fromAmino(object: _184.EnumValueOptionsAmino): _184.EnumValueOptions;
            toAmino(message: _184.EnumValueOptions): _184.EnumValueOptionsAmino;
            fromAminoMsg(object: _184.EnumValueOptionsAminoMsg): _184.EnumValueOptions;
            fromProtoMsg(message: _184.EnumValueOptionsProtoMsg): _184.EnumValueOptions;
            toProto(message: _184.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _184.EnumValueOptions): _184.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _184.ServiceOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.ServiceOptions;
            fromPartial(object: Partial<_184.ServiceOptions>): _184.ServiceOptions;
            fromAmino(object: _184.ServiceOptionsAmino): _184.ServiceOptions;
            toAmino(message: _184.ServiceOptions): _184.ServiceOptionsAmino;
            fromAminoMsg(object: _184.ServiceOptionsAminoMsg): _184.ServiceOptions;
            fromProtoMsg(message: _184.ServiceOptionsProtoMsg): _184.ServiceOptions;
            toProto(message: _184.ServiceOptions): Uint8Array;
            toProtoMsg(message: _184.ServiceOptions): _184.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _184.MethodOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.MethodOptions;
            fromPartial(object: Partial<_184.MethodOptions>): _184.MethodOptions;
            fromAmino(object: _184.MethodOptionsAmino): _184.MethodOptions;
            toAmino(message: _184.MethodOptions): _184.MethodOptionsAmino;
            fromAminoMsg(object: _184.MethodOptionsAminoMsg): _184.MethodOptions;
            fromProtoMsg(message: _184.MethodOptionsProtoMsg): _184.MethodOptions;
            toProto(message: _184.MethodOptions): Uint8Array;
            toProtoMsg(message: _184.MethodOptions): _184.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _184.UninterpretedOption, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.UninterpretedOption;
            fromPartial(object: Partial<_184.UninterpretedOption>): _184.UninterpretedOption;
            fromAmino(object: _184.UninterpretedOptionAmino): _184.UninterpretedOption;
            toAmino(message: _184.UninterpretedOption): _184.UninterpretedOptionAmino;
            fromAminoMsg(object: _184.UninterpretedOptionAminoMsg): _184.UninterpretedOption;
            fromProtoMsg(message: _184.UninterpretedOptionProtoMsg): _184.UninterpretedOption;
            toProto(message: _184.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _184.UninterpretedOption): _184.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _184.UninterpretedOption_NamePart, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_184.UninterpretedOption_NamePart>): _184.UninterpretedOption_NamePart;
            fromAmino(object: _184.UninterpretedOption_NamePartAmino): _184.UninterpretedOption_NamePart;
            toAmino(message: _184.UninterpretedOption_NamePart): _184.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _184.UninterpretedOption_NamePartAminoMsg): _184.UninterpretedOption_NamePart;
            fromProtoMsg(message: _184.UninterpretedOption_NamePartProtoMsg): _184.UninterpretedOption_NamePart;
            toProto(message: _184.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _184.UninterpretedOption_NamePart): _184.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _184.SourceCodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.SourceCodeInfo;
            fromPartial(object: Partial<_184.SourceCodeInfo>): _184.SourceCodeInfo;
            fromAmino(object: _184.SourceCodeInfoAmino): _184.SourceCodeInfo;
            toAmino(message: _184.SourceCodeInfo): _184.SourceCodeInfoAmino;
            fromAminoMsg(object: _184.SourceCodeInfoAminoMsg): _184.SourceCodeInfo;
            fromProtoMsg(message: _184.SourceCodeInfoProtoMsg): _184.SourceCodeInfo;
            toProto(message: _184.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _184.SourceCodeInfo): _184.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _184.SourceCodeInfo_Location, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.SourceCodeInfo_Location;
            fromPartial(object: Partial<_184.SourceCodeInfo_Location>): _184.SourceCodeInfo_Location;
            fromAmino(object: _184.SourceCodeInfo_LocationAmino): _184.SourceCodeInfo_Location;
            toAmino(message: _184.SourceCodeInfo_Location): _184.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _184.SourceCodeInfo_LocationAminoMsg): _184.SourceCodeInfo_Location;
            fromProtoMsg(message: _184.SourceCodeInfo_LocationProtoMsg): _184.SourceCodeInfo_Location;
            toProto(message: _184.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _184.SourceCodeInfo_Location): _184.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _184.GeneratedCodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.GeneratedCodeInfo;
            fromPartial(object: Partial<_184.GeneratedCodeInfo>): _184.GeneratedCodeInfo;
            fromAmino(object: _184.GeneratedCodeInfoAmino): _184.GeneratedCodeInfo;
            toAmino(message: _184.GeneratedCodeInfo): _184.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _184.GeneratedCodeInfoAminoMsg): _184.GeneratedCodeInfo;
            fromProtoMsg(message: _184.GeneratedCodeInfoProtoMsg): _184.GeneratedCodeInfo;
            toProto(message: _184.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _184.GeneratedCodeInfo): _184.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _184.GeneratedCodeInfo_Annotation, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _184.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_184.GeneratedCodeInfo_Annotation>): _184.GeneratedCodeInfo_Annotation;
            fromAmino(object: _184.GeneratedCodeInfo_AnnotationAmino): _184.GeneratedCodeInfo_Annotation;
            toAmino(message: _184.GeneratedCodeInfo_Annotation): _184.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _184.GeneratedCodeInfo_AnnotationAminoMsg): _184.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _184.GeneratedCodeInfo_AnnotationProtoMsg): _184.GeneratedCodeInfo_Annotation;
            toProto(message: _184.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _184.GeneratedCodeInfo_Annotation): _184.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _183.Any, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _183.Any;
            fromPartial(object: Partial<_183.Any>): _183.Any;
            fromAmino(object: _183.AnyAmino): _183.Any;
            toAmino(message: _183.Any): _183.AnyAmino;
            fromAminoMsg(object: _183.AnyAminoMsg): _183.Any;
            fromProtoMsg(message: _183.AnyProtoMsg): _183.Any;
            toProto(message: _183.Any): Uint8Array;
            toProtoMsg(message: _183.Any): _183.AnyProtoMsg;
        };
    };
}
