import * as _174 from "./protobuf/any";
import * as _175 from "./protobuf/descriptor";
import * as _176 from "./protobuf/duration";
import * as _177 from "./protobuf/empty";
import * as _178 from "./protobuf/timestamp";
export declare namespace google {
    const protobuf: {
        Timestamp: {
            typeUrl: string;
            encode(message: _178.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _178.Timestamp;
            fromPartial(object: Partial<_178.Timestamp>): _178.Timestamp;
            fromAmino(object: string): _178.Timestamp;
            toAmino(message: _178.Timestamp): string;
            fromAminoMsg(object: _178.TimestampAminoMsg): _178.Timestamp;
            fromProtoMsg(message: _178.TimestampProtoMsg): _178.Timestamp;
            toProto(message: _178.Timestamp): Uint8Array;
            toProtoMsg(message: _178.Timestamp): _178.TimestampProtoMsg;
        };
        Empty: {
            typeUrl: string;
            encode(_: _177.Empty, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _177.Empty;
            fromPartial(_: Partial<_177.Empty>): _177.Empty;
            fromAmino(_: _177.EmptyAmino): _177.Empty;
            toAmino(_: _177.Empty): _177.EmptyAmino;
            fromAminoMsg(object: _177.EmptyAminoMsg): _177.Empty;
            fromProtoMsg(message: _177.EmptyProtoMsg): _177.Empty;
            toProto(message: _177.Empty): Uint8Array;
            toProtoMsg(message: _177.Empty): _177.EmptyProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _176.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _176.Duration;
            fromPartial(object: Partial<_176.Duration>): _176.Duration;
            fromAmino(object: string): _176.Duration;
            toAmino(message: _176.Duration): string;
            fromAminoMsg(object: _176.DurationAminoMsg): _176.Duration;
            fromProtoMsg(message: _176.DurationProtoMsg): _176.Duration;
            toProto(message: _176.Duration): Uint8Array;
            toProtoMsg(message: _176.Duration): _176.DurationProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _175.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _175.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _175.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _175.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _175.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _175.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _175.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _175.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _175.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _175.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _175.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _175.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _175.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _175.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _175.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _175.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _175.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _175.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _175.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _175.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _175.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _175.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _175.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _175.FieldOptions_CType;
        FieldOptions_JSType: typeof _175.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _175.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _175.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _175.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _175.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _175.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _175.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.FileDescriptorSet;
            fromPartial(object: Partial<_175.FileDescriptorSet>): _175.FileDescriptorSet;
            fromAmino(object: _175.FileDescriptorSetAmino): _175.FileDescriptorSet;
            toAmino(message: _175.FileDescriptorSet): _175.FileDescriptorSetAmino;
            fromAminoMsg(object: _175.FileDescriptorSetAminoMsg): _175.FileDescriptorSet;
            fromProtoMsg(message: _175.FileDescriptorSetProtoMsg): _175.FileDescriptorSet;
            toProto(message: _175.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _175.FileDescriptorSet): _175.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _175.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.FileDescriptorProto;
            fromPartial(object: Partial<_175.FileDescriptorProto>): _175.FileDescriptorProto;
            fromAmino(object: _175.FileDescriptorProtoAmino): _175.FileDescriptorProto;
            toAmino(message: _175.FileDescriptorProto): _175.FileDescriptorProtoAmino;
            fromAminoMsg(object: _175.FileDescriptorProtoAminoMsg): _175.FileDescriptorProto;
            fromProtoMsg(message: _175.FileDescriptorProtoProtoMsg): _175.FileDescriptorProto;
            toProto(message: _175.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _175.FileDescriptorProto): _175.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _175.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.DescriptorProto;
            fromPartial(object: Partial<_175.DescriptorProto>): _175.DescriptorProto;
            fromAmino(object: _175.DescriptorProtoAmino): _175.DescriptorProto;
            toAmino(message: _175.DescriptorProto): _175.DescriptorProtoAmino;
            fromAminoMsg(object: _175.DescriptorProtoAminoMsg): _175.DescriptorProto;
            fromProtoMsg(message: _175.DescriptorProtoProtoMsg): _175.DescriptorProto;
            toProto(message: _175.DescriptorProto): Uint8Array;
            toProtoMsg(message: _175.DescriptorProto): _175.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _175.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_175.DescriptorProto_ExtensionRange>): _175.DescriptorProto_ExtensionRange;
            fromAmino(object: _175.DescriptorProto_ExtensionRangeAmino): _175.DescriptorProto_ExtensionRange;
            toAmino(message: _175.DescriptorProto_ExtensionRange): _175.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _175.DescriptorProto_ExtensionRangeAminoMsg): _175.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _175.DescriptorProto_ExtensionRangeProtoMsg): _175.DescriptorProto_ExtensionRange;
            toProto(message: _175.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _175.DescriptorProto_ExtensionRange): _175.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _175.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_175.DescriptorProto_ReservedRange>): _175.DescriptorProto_ReservedRange;
            fromAmino(object: _175.DescriptorProto_ReservedRangeAmino): _175.DescriptorProto_ReservedRange;
            toAmino(message: _175.DescriptorProto_ReservedRange): _175.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _175.DescriptorProto_ReservedRangeAminoMsg): _175.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _175.DescriptorProto_ReservedRangeProtoMsg): _175.DescriptorProto_ReservedRange;
            toProto(message: _175.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _175.DescriptorProto_ReservedRange): _175.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _175.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.ExtensionRangeOptions;
            fromPartial(object: Partial<_175.ExtensionRangeOptions>): _175.ExtensionRangeOptions;
            fromAmino(object: _175.ExtensionRangeOptionsAmino): _175.ExtensionRangeOptions;
            toAmino(message: _175.ExtensionRangeOptions): _175.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _175.ExtensionRangeOptionsAminoMsg): _175.ExtensionRangeOptions;
            fromProtoMsg(message: _175.ExtensionRangeOptionsProtoMsg): _175.ExtensionRangeOptions;
            toProto(message: _175.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _175.ExtensionRangeOptions): _175.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _175.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.FieldDescriptorProto;
            fromPartial(object: Partial<_175.FieldDescriptorProto>): _175.FieldDescriptorProto;
            fromAmino(object: _175.FieldDescriptorProtoAmino): _175.FieldDescriptorProto;
            toAmino(message: _175.FieldDescriptorProto): _175.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _175.FieldDescriptorProtoAminoMsg): _175.FieldDescriptorProto;
            fromProtoMsg(message: _175.FieldDescriptorProtoProtoMsg): _175.FieldDescriptorProto;
            toProto(message: _175.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _175.FieldDescriptorProto): _175.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _175.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.OneofDescriptorProto;
            fromPartial(object: Partial<_175.OneofDescriptorProto>): _175.OneofDescriptorProto;
            fromAmino(object: _175.OneofDescriptorProtoAmino): _175.OneofDescriptorProto;
            toAmino(message: _175.OneofDescriptorProto): _175.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _175.OneofDescriptorProtoAminoMsg): _175.OneofDescriptorProto;
            fromProtoMsg(message: _175.OneofDescriptorProtoProtoMsg): _175.OneofDescriptorProto;
            toProto(message: _175.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _175.OneofDescriptorProto): _175.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _175.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.EnumDescriptorProto;
            fromPartial(object: Partial<_175.EnumDescriptorProto>): _175.EnumDescriptorProto;
            fromAmino(object: _175.EnumDescriptorProtoAmino): _175.EnumDescriptorProto;
            toAmino(message: _175.EnumDescriptorProto): _175.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _175.EnumDescriptorProtoAminoMsg): _175.EnumDescriptorProto;
            fromProtoMsg(message: _175.EnumDescriptorProtoProtoMsg): _175.EnumDescriptorProto;
            toProto(message: _175.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _175.EnumDescriptorProto): _175.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _175.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_175.EnumDescriptorProto_EnumReservedRange>): _175.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _175.EnumDescriptorProto_EnumReservedRangeAmino): _175.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _175.EnumDescriptorProto_EnumReservedRange): _175.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _175.EnumDescriptorProto_EnumReservedRangeAminoMsg): _175.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _175.EnumDescriptorProto_EnumReservedRangeProtoMsg): _175.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _175.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _175.EnumDescriptorProto_EnumReservedRange): _175.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _175.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.EnumValueDescriptorProto;
            fromPartial(object: Partial<_175.EnumValueDescriptorProto>): _175.EnumValueDescriptorProto;
            fromAmino(object: _175.EnumValueDescriptorProtoAmino): _175.EnumValueDescriptorProto;
            toAmino(message: _175.EnumValueDescriptorProto): _175.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _175.EnumValueDescriptorProtoAminoMsg): _175.EnumValueDescriptorProto;
            fromProtoMsg(message: _175.EnumValueDescriptorProtoProtoMsg): _175.EnumValueDescriptorProto;
            toProto(message: _175.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _175.EnumValueDescriptorProto): _175.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _175.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.ServiceDescriptorProto;
            fromPartial(object: Partial<_175.ServiceDescriptorProto>): _175.ServiceDescriptorProto;
            fromAmino(object: _175.ServiceDescriptorProtoAmino): _175.ServiceDescriptorProto;
            toAmino(message: _175.ServiceDescriptorProto): _175.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _175.ServiceDescriptorProtoAminoMsg): _175.ServiceDescriptorProto;
            fromProtoMsg(message: _175.ServiceDescriptorProtoProtoMsg): _175.ServiceDescriptorProto;
            toProto(message: _175.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _175.ServiceDescriptorProto): _175.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _175.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.MethodDescriptorProto;
            fromPartial(object: Partial<_175.MethodDescriptorProto>): _175.MethodDescriptorProto;
            fromAmino(object: _175.MethodDescriptorProtoAmino): _175.MethodDescriptorProto;
            toAmino(message: _175.MethodDescriptorProto): _175.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _175.MethodDescriptorProtoAminoMsg): _175.MethodDescriptorProto;
            fromProtoMsg(message: _175.MethodDescriptorProtoProtoMsg): _175.MethodDescriptorProto;
            toProto(message: _175.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _175.MethodDescriptorProto): _175.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _175.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.FileOptions;
            fromPartial(object: Partial<_175.FileOptions>): _175.FileOptions;
            fromAmino(object: _175.FileOptionsAmino): _175.FileOptions;
            toAmino(message: _175.FileOptions): _175.FileOptionsAmino;
            fromAminoMsg(object: _175.FileOptionsAminoMsg): _175.FileOptions;
            fromProtoMsg(message: _175.FileOptionsProtoMsg): _175.FileOptions;
            toProto(message: _175.FileOptions): Uint8Array;
            toProtoMsg(message: _175.FileOptions): _175.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _175.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.MessageOptions;
            fromPartial(object: Partial<_175.MessageOptions>): _175.MessageOptions;
            fromAmino(object: _175.MessageOptionsAmino): _175.MessageOptions;
            toAmino(message: _175.MessageOptions): _175.MessageOptionsAmino;
            fromAminoMsg(object: _175.MessageOptionsAminoMsg): _175.MessageOptions;
            fromProtoMsg(message: _175.MessageOptionsProtoMsg): _175.MessageOptions;
            toProto(message: _175.MessageOptions): Uint8Array;
            toProtoMsg(message: _175.MessageOptions): _175.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _175.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.FieldOptions;
            fromPartial(object: Partial<_175.FieldOptions>): _175.FieldOptions;
            fromAmino(object: _175.FieldOptionsAmino): _175.FieldOptions;
            toAmino(message: _175.FieldOptions): _175.FieldOptionsAmino;
            fromAminoMsg(object: _175.FieldOptionsAminoMsg): _175.FieldOptions;
            fromProtoMsg(message: _175.FieldOptionsProtoMsg): _175.FieldOptions;
            toProto(message: _175.FieldOptions): Uint8Array;
            toProtoMsg(message: _175.FieldOptions): _175.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _175.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.OneofOptions;
            fromPartial(object: Partial<_175.OneofOptions>): _175.OneofOptions;
            fromAmino(object: _175.OneofOptionsAmino): _175.OneofOptions;
            toAmino(message: _175.OneofOptions): _175.OneofOptionsAmino;
            fromAminoMsg(object: _175.OneofOptionsAminoMsg): _175.OneofOptions;
            fromProtoMsg(message: _175.OneofOptionsProtoMsg): _175.OneofOptions;
            toProto(message: _175.OneofOptions): Uint8Array;
            toProtoMsg(message: _175.OneofOptions): _175.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _175.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.EnumOptions;
            fromPartial(object: Partial<_175.EnumOptions>): _175.EnumOptions;
            fromAmino(object: _175.EnumOptionsAmino): _175.EnumOptions;
            toAmino(message: _175.EnumOptions): _175.EnumOptionsAmino;
            fromAminoMsg(object: _175.EnumOptionsAminoMsg): _175.EnumOptions;
            fromProtoMsg(message: _175.EnumOptionsProtoMsg): _175.EnumOptions;
            toProto(message: _175.EnumOptions): Uint8Array;
            toProtoMsg(message: _175.EnumOptions): _175.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _175.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.EnumValueOptions;
            fromPartial(object: Partial<_175.EnumValueOptions>): _175.EnumValueOptions;
            fromAmino(object: _175.EnumValueOptionsAmino): _175.EnumValueOptions;
            toAmino(message: _175.EnumValueOptions): _175.EnumValueOptionsAmino;
            fromAminoMsg(object: _175.EnumValueOptionsAminoMsg): _175.EnumValueOptions;
            fromProtoMsg(message: _175.EnumValueOptionsProtoMsg): _175.EnumValueOptions;
            toProto(message: _175.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _175.EnumValueOptions): _175.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _175.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.ServiceOptions;
            fromPartial(object: Partial<_175.ServiceOptions>): _175.ServiceOptions;
            fromAmino(object: _175.ServiceOptionsAmino): _175.ServiceOptions;
            toAmino(message: _175.ServiceOptions): _175.ServiceOptionsAmino;
            fromAminoMsg(object: _175.ServiceOptionsAminoMsg): _175.ServiceOptions;
            fromProtoMsg(message: _175.ServiceOptionsProtoMsg): _175.ServiceOptions;
            toProto(message: _175.ServiceOptions): Uint8Array;
            toProtoMsg(message: _175.ServiceOptions): _175.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _175.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.MethodOptions;
            fromPartial(object: Partial<_175.MethodOptions>): _175.MethodOptions;
            fromAmino(object: _175.MethodOptionsAmino): _175.MethodOptions;
            toAmino(message: _175.MethodOptions): _175.MethodOptionsAmino;
            fromAminoMsg(object: _175.MethodOptionsAminoMsg): _175.MethodOptions;
            fromProtoMsg(message: _175.MethodOptionsProtoMsg): _175.MethodOptions;
            toProto(message: _175.MethodOptions): Uint8Array;
            toProtoMsg(message: _175.MethodOptions): _175.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _175.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.UninterpretedOption;
            fromPartial(object: Partial<_175.UninterpretedOption>): _175.UninterpretedOption;
            fromAmino(object: _175.UninterpretedOptionAmino): _175.UninterpretedOption;
            toAmino(message: _175.UninterpretedOption): _175.UninterpretedOptionAmino;
            fromAminoMsg(object: _175.UninterpretedOptionAminoMsg): _175.UninterpretedOption;
            fromProtoMsg(message: _175.UninterpretedOptionProtoMsg): _175.UninterpretedOption;
            toProto(message: _175.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _175.UninterpretedOption): _175.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _175.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_175.UninterpretedOption_NamePart>): _175.UninterpretedOption_NamePart;
            fromAmino(object: _175.UninterpretedOption_NamePartAmino): _175.UninterpretedOption_NamePart;
            toAmino(message: _175.UninterpretedOption_NamePart): _175.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _175.UninterpretedOption_NamePartAminoMsg): _175.UninterpretedOption_NamePart;
            fromProtoMsg(message: _175.UninterpretedOption_NamePartProtoMsg): _175.UninterpretedOption_NamePart;
            toProto(message: _175.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _175.UninterpretedOption_NamePart): _175.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _175.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.SourceCodeInfo;
            fromPartial(object: Partial<_175.SourceCodeInfo>): _175.SourceCodeInfo;
            fromAmino(object: _175.SourceCodeInfoAmino): _175.SourceCodeInfo;
            toAmino(message: _175.SourceCodeInfo): _175.SourceCodeInfoAmino;
            fromAminoMsg(object: _175.SourceCodeInfoAminoMsg): _175.SourceCodeInfo;
            fromProtoMsg(message: _175.SourceCodeInfoProtoMsg): _175.SourceCodeInfo;
            toProto(message: _175.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _175.SourceCodeInfo): _175.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _175.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.SourceCodeInfo_Location;
            fromPartial(object: Partial<_175.SourceCodeInfo_Location>): _175.SourceCodeInfo_Location;
            fromAmino(object: _175.SourceCodeInfo_LocationAmino): _175.SourceCodeInfo_Location;
            toAmino(message: _175.SourceCodeInfo_Location): _175.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _175.SourceCodeInfo_LocationAminoMsg): _175.SourceCodeInfo_Location;
            fromProtoMsg(message: _175.SourceCodeInfo_LocationProtoMsg): _175.SourceCodeInfo_Location;
            toProto(message: _175.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _175.SourceCodeInfo_Location): _175.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _175.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.GeneratedCodeInfo;
            fromPartial(object: Partial<_175.GeneratedCodeInfo>): _175.GeneratedCodeInfo;
            fromAmino(object: _175.GeneratedCodeInfoAmino): _175.GeneratedCodeInfo;
            toAmino(message: _175.GeneratedCodeInfo): _175.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _175.GeneratedCodeInfoAminoMsg): _175.GeneratedCodeInfo;
            fromProtoMsg(message: _175.GeneratedCodeInfoProtoMsg): _175.GeneratedCodeInfo;
            toProto(message: _175.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _175.GeneratedCodeInfo): _175.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _175.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _175.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_175.GeneratedCodeInfo_Annotation>): _175.GeneratedCodeInfo_Annotation;
            fromAmino(object: _175.GeneratedCodeInfo_AnnotationAmino): _175.GeneratedCodeInfo_Annotation;
            toAmino(message: _175.GeneratedCodeInfo_Annotation): _175.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _175.GeneratedCodeInfo_AnnotationAminoMsg): _175.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _175.GeneratedCodeInfo_AnnotationProtoMsg): _175.GeneratedCodeInfo_Annotation;
            toProto(message: _175.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _175.GeneratedCodeInfo_Annotation): _175.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _174.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number): _174.Any;
            fromPartial(object: Partial<_174.Any>): _174.Any;
            fromAmino(object: _174.AnyAmino): _174.Any;
            toAmino(message: _174.Any): _174.AnyAmino;
            fromAminoMsg(object: _174.AnyAminoMsg): _174.Any;
            fromProtoMsg(message: _174.AnyProtoMsg): _174.Any;
            toProto(message: _174.Any): Uint8Array;
            toProtoMsg(message: _174.Any): _174.AnyProtoMsg;
        };
    };
}
