import * as _46 from "./abci/types";
import * as _47 from "./crypto/keys";
import * as _48 from "./crypto/proof";
import * as _49 from "./libs/bits/types";
import * as _50 from "./p2p/types";
import * as _51 from "./types/block";
import * as _52 from "./types/evidence";
import * as _53 from "./types/params";
import * as _54 from "./types/types";
import * as _55 from "./types/validator";
import * as _56 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _46.CheckTxType;
        checkTxTypeToJSON(object: _46.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _46.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _46.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _46.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _46.ResponseApplySnapshotChunk_Result): string;
        responseProcessProposal_ProposalStatusFromJSON(object: any): _46.ResponseProcessProposal_ProposalStatus;
        responseProcessProposal_ProposalStatusToJSON(object: _46.ResponseProcessProposal_ProposalStatus): string;
        misbehaviorTypeFromJSON(object: any): _46.MisbehaviorType;
        misbehaviorTypeToJSON(object: _46.MisbehaviorType): string;
        CheckTxType: typeof _46.CheckTxType;
        CheckTxTypeSDKType: typeof _46.CheckTxType;
        CheckTxTypeAmino: typeof _46.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _46.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _46.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _46.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _46.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _46.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _46.ResponseApplySnapshotChunk_Result;
        ResponseProcessProposal_ProposalStatus: typeof _46.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusSDKType: typeof _46.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusAmino: typeof _46.ResponseProcessProposal_ProposalStatus;
        MisbehaviorType: typeof _46.MisbehaviorType;
        MisbehaviorTypeSDKType: typeof _46.MisbehaviorType;
        MisbehaviorTypeAmino: typeof _46.MisbehaviorType;
        Request: {
            typeUrl: string;
            encode(message: _46.Request, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.Request;
            fromPartial(object: Partial<_46.Request>): _46.Request;
            fromAmino(object: _46.RequestAmino): _46.Request;
            toAmino(message: _46.Request): _46.RequestAmino;
            fromAminoMsg(object: _46.RequestAminoMsg): _46.Request;
            fromProtoMsg(message: _46.RequestProtoMsg): _46.Request;
            toProto(message: _46.Request): Uint8Array;
            toProtoMsg(message: _46.Request): _46.RequestProtoMsg;
        };
        RequestEcho: {
            typeUrl: string;
            encode(message: _46.RequestEcho, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.RequestEcho;
            fromPartial(object: Partial<_46.RequestEcho>): _46.RequestEcho;
            fromAmino(object: _46.RequestEchoAmino): _46.RequestEcho;
            toAmino(message: _46.RequestEcho): _46.RequestEchoAmino;
            fromAminoMsg(object: _46.RequestEchoAminoMsg): _46.RequestEcho;
            fromProtoMsg(message: _46.RequestEchoProtoMsg): _46.RequestEcho;
            toProto(message: _46.RequestEcho): Uint8Array;
            toProtoMsg(message: _46.RequestEcho): _46.RequestEchoProtoMsg;
        };
        RequestFlush: {
            typeUrl: string;
            encode(_: _46.RequestFlush, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.RequestFlush;
            fromPartial(_: Partial<_46.RequestFlush>): _46.RequestFlush;
            fromAmino(_: _46.RequestFlushAmino): _46.RequestFlush;
            toAmino(_: _46.RequestFlush): _46.RequestFlushAmino;
            fromAminoMsg(object: _46.RequestFlushAminoMsg): _46.RequestFlush;
            fromProtoMsg(message: _46.RequestFlushProtoMsg): _46.RequestFlush;
            toProto(message: _46.RequestFlush): Uint8Array;
            toProtoMsg(message: _46.RequestFlush): _46.RequestFlushProtoMsg;
        };
        RequestInfo: {
            typeUrl: string;
            encode(message: _46.RequestInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.RequestInfo;
            fromPartial(object: Partial<_46.RequestInfo>): _46.RequestInfo;
            fromAmino(object: _46.RequestInfoAmino): _46.RequestInfo;
            toAmino(message: _46.RequestInfo): _46.RequestInfoAmino;
            fromAminoMsg(object: _46.RequestInfoAminoMsg): _46.RequestInfo;
            fromProtoMsg(message: _46.RequestInfoProtoMsg): _46.RequestInfo;
            toProto(message: _46.RequestInfo): Uint8Array;
            toProtoMsg(message: _46.RequestInfo): _46.RequestInfoProtoMsg;
        };
        RequestInitChain: {
            typeUrl: string;
            encode(message: _46.RequestInitChain, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.RequestInitChain;
            fromPartial(object: Partial<_46.RequestInitChain>): _46.RequestInitChain;
            fromAmino(object: _46.RequestInitChainAmino): _46.RequestInitChain;
            toAmino(message: _46.RequestInitChain): _46.RequestInitChainAmino;
            fromAminoMsg(object: _46.RequestInitChainAminoMsg): _46.RequestInitChain;
            fromProtoMsg(message: _46.RequestInitChainProtoMsg): _46.RequestInitChain;
            toProto(message: _46.RequestInitChain): Uint8Array;
            toProtoMsg(message: _46.RequestInitChain): _46.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            typeUrl: string;
            encode(message: _46.RequestQuery, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.RequestQuery;
            fromPartial(object: Partial<_46.RequestQuery>): _46.RequestQuery;
            fromAmino(object: _46.RequestQueryAmino): _46.RequestQuery;
            toAmino(message: _46.RequestQuery): _46.RequestQueryAmino;
            fromAminoMsg(object: _46.RequestQueryAminoMsg): _46.RequestQuery;
            fromProtoMsg(message: _46.RequestQueryProtoMsg): _46.RequestQuery;
            toProto(message: _46.RequestQuery): Uint8Array;
            toProtoMsg(message: _46.RequestQuery): _46.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            typeUrl: string;
            encode(message: _46.RequestBeginBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.RequestBeginBlock;
            fromPartial(object: Partial<_46.RequestBeginBlock>): _46.RequestBeginBlock;
            fromAmino(object: _46.RequestBeginBlockAmino): _46.RequestBeginBlock;
            toAmino(message: _46.RequestBeginBlock): _46.RequestBeginBlockAmino;
            fromAminoMsg(object: _46.RequestBeginBlockAminoMsg): _46.RequestBeginBlock;
            fromProtoMsg(message: _46.RequestBeginBlockProtoMsg): _46.RequestBeginBlock;
            toProto(message: _46.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _46.RequestBeginBlock): _46.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            typeUrl: string;
            encode(message: _46.RequestCheckTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.RequestCheckTx;
            fromPartial(object: Partial<_46.RequestCheckTx>): _46.RequestCheckTx;
            fromAmino(object: _46.RequestCheckTxAmino): _46.RequestCheckTx;
            toAmino(message: _46.RequestCheckTx): _46.RequestCheckTxAmino;
            fromAminoMsg(object: _46.RequestCheckTxAminoMsg): _46.RequestCheckTx;
            fromProtoMsg(message: _46.RequestCheckTxProtoMsg): _46.RequestCheckTx;
            toProto(message: _46.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _46.RequestCheckTx): _46.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            typeUrl: string;
            encode(message: _46.RequestDeliverTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.RequestDeliverTx;
            fromPartial(object: Partial<_46.RequestDeliverTx>): _46.RequestDeliverTx;
            fromAmino(object: _46.RequestDeliverTxAmino): _46.RequestDeliverTx;
            toAmino(message: _46.RequestDeliverTx): _46.RequestDeliverTxAmino;
            fromAminoMsg(object: _46.RequestDeliverTxAminoMsg): _46.RequestDeliverTx;
            fromProtoMsg(message: _46.RequestDeliverTxProtoMsg): _46.RequestDeliverTx;
            toProto(message: _46.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _46.RequestDeliverTx): _46.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            typeUrl: string;
            encode(message: _46.RequestEndBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.RequestEndBlock;
            fromPartial(object: Partial<_46.RequestEndBlock>): _46.RequestEndBlock;
            fromAmino(object: _46.RequestEndBlockAmino): _46.RequestEndBlock;
            toAmino(message: _46.RequestEndBlock): _46.RequestEndBlockAmino;
            fromAminoMsg(object: _46.RequestEndBlockAminoMsg): _46.RequestEndBlock;
            fromProtoMsg(message: _46.RequestEndBlockProtoMsg): _46.RequestEndBlock;
            toProto(message: _46.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _46.RequestEndBlock): _46.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            typeUrl: string;
            encode(_: _46.RequestCommit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.RequestCommit;
            fromPartial(_: Partial<_46.RequestCommit>): _46.RequestCommit;
            fromAmino(_: _46.RequestCommitAmino): _46.RequestCommit;
            toAmino(_: _46.RequestCommit): _46.RequestCommitAmino;
            fromAminoMsg(object: _46.RequestCommitAminoMsg): _46.RequestCommit;
            fromProtoMsg(message: _46.RequestCommitProtoMsg): _46.RequestCommit;
            toProto(message: _46.RequestCommit): Uint8Array;
            toProtoMsg(message: _46.RequestCommit): _46.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            typeUrl: string;
            encode(_: _46.RequestListSnapshots, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.RequestListSnapshots;
            fromPartial(_: Partial<_46.RequestListSnapshots>): _46.RequestListSnapshots;
            fromAmino(_: _46.RequestListSnapshotsAmino): _46.RequestListSnapshots;
            toAmino(_: _46.RequestListSnapshots): _46.RequestListSnapshotsAmino;
            fromAminoMsg(object: _46.RequestListSnapshotsAminoMsg): _46.RequestListSnapshots;
            fromProtoMsg(message: _46.RequestListSnapshotsProtoMsg): _46.RequestListSnapshots;
            toProto(message: _46.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _46.RequestListSnapshots): _46.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            typeUrl: string;
            encode(message: _46.RequestOfferSnapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.RequestOfferSnapshot;
            fromPartial(object: Partial<_46.RequestOfferSnapshot>): _46.RequestOfferSnapshot;
            fromAmino(object: _46.RequestOfferSnapshotAmino): _46.RequestOfferSnapshot;
            toAmino(message: _46.RequestOfferSnapshot): _46.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _46.RequestOfferSnapshotAminoMsg): _46.RequestOfferSnapshot;
            fromProtoMsg(message: _46.RequestOfferSnapshotProtoMsg): _46.RequestOfferSnapshot;
            toProto(message: _46.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _46.RequestOfferSnapshot): _46.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _46.RequestLoadSnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.RequestLoadSnapshotChunk;
            fromPartial(object: Partial<_46.RequestLoadSnapshotChunk>): _46.RequestLoadSnapshotChunk;
            fromAmino(object: _46.RequestLoadSnapshotChunkAmino): _46.RequestLoadSnapshotChunk;
            toAmino(message: _46.RequestLoadSnapshotChunk): _46.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _46.RequestLoadSnapshotChunkAminoMsg): _46.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _46.RequestLoadSnapshotChunkProtoMsg): _46.RequestLoadSnapshotChunk;
            toProto(message: _46.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _46.RequestLoadSnapshotChunk): _46.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _46.RequestApplySnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.RequestApplySnapshotChunk;
            fromPartial(object: Partial<_46.RequestApplySnapshotChunk>): _46.RequestApplySnapshotChunk;
            fromAmino(object: _46.RequestApplySnapshotChunkAmino): _46.RequestApplySnapshotChunk;
            toAmino(message: _46.RequestApplySnapshotChunk): _46.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _46.RequestApplySnapshotChunkAminoMsg): _46.RequestApplySnapshotChunk;
            fromProtoMsg(message: _46.RequestApplySnapshotChunkProtoMsg): _46.RequestApplySnapshotChunk;
            toProto(message: _46.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _46.RequestApplySnapshotChunk): _46.RequestApplySnapshotChunkProtoMsg;
        };
        RequestPrepareProposal: {
            typeUrl: string;
            encode(message: _46.RequestPrepareProposal, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.RequestPrepareProposal;
            fromPartial(object: Partial<_46.RequestPrepareProposal>): _46.RequestPrepareProposal;
            fromAmino(object: _46.RequestPrepareProposalAmino): _46.RequestPrepareProposal;
            toAmino(message: _46.RequestPrepareProposal): _46.RequestPrepareProposalAmino;
            fromAminoMsg(object: _46.RequestPrepareProposalAminoMsg): _46.RequestPrepareProposal;
            fromProtoMsg(message: _46.RequestPrepareProposalProtoMsg): _46.RequestPrepareProposal;
            toProto(message: _46.RequestPrepareProposal): Uint8Array;
            toProtoMsg(message: _46.RequestPrepareProposal): _46.RequestPrepareProposalProtoMsg;
        };
        RequestProcessProposal: {
            typeUrl: string;
            encode(message: _46.RequestProcessProposal, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.RequestProcessProposal;
            fromPartial(object: Partial<_46.RequestProcessProposal>): _46.RequestProcessProposal;
            fromAmino(object: _46.RequestProcessProposalAmino): _46.RequestProcessProposal;
            toAmino(message: _46.RequestProcessProposal): _46.RequestProcessProposalAmino;
            fromAminoMsg(object: _46.RequestProcessProposalAminoMsg): _46.RequestProcessProposal;
            fromProtoMsg(message: _46.RequestProcessProposalProtoMsg): _46.RequestProcessProposal;
            toProto(message: _46.RequestProcessProposal): Uint8Array;
            toProtoMsg(message: _46.RequestProcessProposal): _46.RequestProcessProposalProtoMsg;
        };
        Response: {
            typeUrl: string;
            encode(message: _46.Response, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.Response;
            fromPartial(object: Partial<_46.Response>): _46.Response;
            fromAmino(object: _46.ResponseAmino): _46.Response;
            toAmino(message: _46.Response): _46.ResponseAmino;
            fromAminoMsg(object: _46.ResponseAminoMsg): _46.Response;
            fromProtoMsg(message: _46.ResponseProtoMsg): _46.Response;
            toProto(message: _46.Response): Uint8Array;
            toProtoMsg(message: _46.Response): _46.ResponseProtoMsg;
        };
        ResponseException: {
            typeUrl: string;
            encode(message: _46.ResponseException, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ResponseException;
            fromPartial(object: Partial<_46.ResponseException>): _46.ResponseException;
            fromAmino(object: _46.ResponseExceptionAmino): _46.ResponseException;
            toAmino(message: _46.ResponseException): _46.ResponseExceptionAmino;
            fromAminoMsg(object: _46.ResponseExceptionAminoMsg): _46.ResponseException;
            fromProtoMsg(message: _46.ResponseExceptionProtoMsg): _46.ResponseException;
            toProto(message: _46.ResponseException): Uint8Array;
            toProtoMsg(message: _46.ResponseException): _46.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            typeUrl: string;
            encode(message: _46.ResponseEcho, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ResponseEcho;
            fromPartial(object: Partial<_46.ResponseEcho>): _46.ResponseEcho;
            fromAmino(object: _46.ResponseEchoAmino): _46.ResponseEcho;
            toAmino(message: _46.ResponseEcho): _46.ResponseEchoAmino;
            fromAminoMsg(object: _46.ResponseEchoAminoMsg): _46.ResponseEcho;
            fromProtoMsg(message: _46.ResponseEchoProtoMsg): _46.ResponseEcho;
            toProto(message: _46.ResponseEcho): Uint8Array;
            toProtoMsg(message: _46.ResponseEcho): _46.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            typeUrl: string;
            encode(_: _46.ResponseFlush, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ResponseFlush;
            fromPartial(_: Partial<_46.ResponseFlush>): _46.ResponseFlush;
            fromAmino(_: _46.ResponseFlushAmino): _46.ResponseFlush;
            toAmino(_: _46.ResponseFlush): _46.ResponseFlushAmino;
            fromAminoMsg(object: _46.ResponseFlushAminoMsg): _46.ResponseFlush;
            fromProtoMsg(message: _46.ResponseFlushProtoMsg): _46.ResponseFlush;
            toProto(message: _46.ResponseFlush): Uint8Array;
            toProtoMsg(message: _46.ResponseFlush): _46.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            typeUrl: string;
            encode(message: _46.ResponseInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ResponseInfo;
            fromPartial(object: Partial<_46.ResponseInfo>): _46.ResponseInfo;
            fromAmino(object: _46.ResponseInfoAmino): _46.ResponseInfo;
            toAmino(message: _46.ResponseInfo): _46.ResponseInfoAmino;
            fromAminoMsg(object: _46.ResponseInfoAminoMsg): _46.ResponseInfo;
            fromProtoMsg(message: _46.ResponseInfoProtoMsg): _46.ResponseInfo;
            toProto(message: _46.ResponseInfo): Uint8Array;
            toProtoMsg(message: _46.ResponseInfo): _46.ResponseInfoProtoMsg;
        };
        ResponseInitChain: {
            typeUrl: string;
            encode(message: _46.ResponseInitChain, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ResponseInitChain;
            fromPartial(object: Partial<_46.ResponseInitChain>): _46.ResponseInitChain;
            fromAmino(object: _46.ResponseInitChainAmino): _46.ResponseInitChain;
            toAmino(message: _46.ResponseInitChain): _46.ResponseInitChainAmino;
            fromAminoMsg(object: _46.ResponseInitChainAminoMsg): _46.ResponseInitChain;
            fromProtoMsg(message: _46.ResponseInitChainProtoMsg): _46.ResponseInitChain;
            toProto(message: _46.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _46.ResponseInitChain): _46.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            typeUrl: string;
            encode(message: _46.ResponseQuery, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ResponseQuery;
            fromPartial(object: Partial<_46.ResponseQuery>): _46.ResponseQuery;
            fromAmino(object: _46.ResponseQueryAmino): _46.ResponseQuery;
            toAmino(message: _46.ResponseQuery): _46.ResponseQueryAmino;
            fromAminoMsg(object: _46.ResponseQueryAminoMsg): _46.ResponseQuery;
            fromProtoMsg(message: _46.ResponseQueryProtoMsg): _46.ResponseQuery;
            toProto(message: _46.ResponseQuery): Uint8Array;
            toProtoMsg(message: _46.ResponseQuery): _46.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            typeUrl: string;
            encode(message: _46.ResponseBeginBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ResponseBeginBlock;
            fromPartial(object: Partial<_46.ResponseBeginBlock>): _46.ResponseBeginBlock;
            fromAmino(object: _46.ResponseBeginBlockAmino): _46.ResponseBeginBlock;
            toAmino(message: _46.ResponseBeginBlock): _46.ResponseBeginBlockAmino;
            fromAminoMsg(object: _46.ResponseBeginBlockAminoMsg): _46.ResponseBeginBlock;
            fromProtoMsg(message: _46.ResponseBeginBlockProtoMsg): _46.ResponseBeginBlock;
            toProto(message: _46.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _46.ResponseBeginBlock): _46.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            typeUrl: string;
            encode(message: _46.ResponseCheckTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ResponseCheckTx;
            fromPartial(object: Partial<_46.ResponseCheckTx>): _46.ResponseCheckTx;
            fromAmino(object: _46.ResponseCheckTxAmino): _46.ResponseCheckTx;
            toAmino(message: _46.ResponseCheckTx): _46.ResponseCheckTxAmino;
            fromAminoMsg(object: _46.ResponseCheckTxAminoMsg): _46.ResponseCheckTx;
            fromProtoMsg(message: _46.ResponseCheckTxProtoMsg): _46.ResponseCheckTx;
            toProto(message: _46.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _46.ResponseCheckTx): _46.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            typeUrl: string;
            encode(message: _46.ResponseDeliverTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ResponseDeliverTx;
            fromPartial(object: Partial<_46.ResponseDeliverTx>): _46.ResponseDeliverTx;
            fromAmino(object: _46.ResponseDeliverTxAmino): _46.ResponseDeliverTx;
            toAmino(message: _46.ResponseDeliverTx): _46.ResponseDeliverTxAmino;
            fromAminoMsg(object: _46.ResponseDeliverTxAminoMsg): _46.ResponseDeliverTx;
            fromProtoMsg(message: _46.ResponseDeliverTxProtoMsg): _46.ResponseDeliverTx;
            toProto(message: _46.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _46.ResponseDeliverTx): _46.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            typeUrl: string;
            encode(message: _46.ResponseEndBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ResponseEndBlock;
            fromPartial(object: Partial<_46.ResponseEndBlock>): _46.ResponseEndBlock;
            fromAmino(object: _46.ResponseEndBlockAmino): _46.ResponseEndBlock;
            toAmino(message: _46.ResponseEndBlock): _46.ResponseEndBlockAmino;
            fromAminoMsg(object: _46.ResponseEndBlockAminoMsg): _46.ResponseEndBlock;
            fromProtoMsg(message: _46.ResponseEndBlockProtoMsg): _46.ResponseEndBlock;
            toProto(message: _46.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _46.ResponseEndBlock): _46.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            typeUrl: string;
            encode(message: _46.ResponseCommit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ResponseCommit;
            fromPartial(object: Partial<_46.ResponseCommit>): _46.ResponseCommit;
            fromAmino(object: _46.ResponseCommitAmino): _46.ResponseCommit;
            toAmino(message: _46.ResponseCommit): _46.ResponseCommitAmino;
            fromAminoMsg(object: _46.ResponseCommitAminoMsg): _46.ResponseCommit;
            fromProtoMsg(message: _46.ResponseCommitProtoMsg): _46.ResponseCommit;
            toProto(message: _46.ResponseCommit): Uint8Array;
            toProtoMsg(message: _46.ResponseCommit): _46.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            typeUrl: string;
            encode(message: _46.ResponseListSnapshots, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ResponseListSnapshots;
            fromPartial(object: Partial<_46.ResponseListSnapshots>): _46.ResponseListSnapshots;
            fromAmino(object: _46.ResponseListSnapshotsAmino): _46.ResponseListSnapshots;
            toAmino(message: _46.ResponseListSnapshots): _46.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _46.ResponseListSnapshotsAminoMsg): _46.ResponseListSnapshots;
            fromProtoMsg(message: _46.ResponseListSnapshotsProtoMsg): _46.ResponseListSnapshots;
            toProto(message: _46.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _46.ResponseListSnapshots): _46.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            typeUrl: string;
            encode(message: _46.ResponseOfferSnapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ResponseOfferSnapshot;
            fromPartial(object: Partial<_46.ResponseOfferSnapshot>): _46.ResponseOfferSnapshot;
            fromAmino(object: _46.ResponseOfferSnapshotAmino): _46.ResponseOfferSnapshot;
            toAmino(message: _46.ResponseOfferSnapshot): _46.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _46.ResponseOfferSnapshotAminoMsg): _46.ResponseOfferSnapshot;
            fromProtoMsg(message: _46.ResponseOfferSnapshotProtoMsg): _46.ResponseOfferSnapshot;
            toProto(message: _46.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _46.ResponseOfferSnapshot): _46.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _46.ResponseLoadSnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ResponseLoadSnapshotChunk;
            fromPartial(object: Partial<_46.ResponseLoadSnapshotChunk>): _46.ResponseLoadSnapshotChunk;
            fromAmino(object: _46.ResponseLoadSnapshotChunkAmino): _46.ResponseLoadSnapshotChunk;
            toAmino(message: _46.ResponseLoadSnapshotChunk): _46.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _46.ResponseLoadSnapshotChunkAminoMsg): _46.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _46.ResponseLoadSnapshotChunkProtoMsg): _46.ResponseLoadSnapshotChunk;
            toProto(message: _46.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _46.ResponseLoadSnapshotChunk): _46.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _46.ResponseApplySnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ResponseApplySnapshotChunk;
            fromPartial(object: Partial<_46.ResponseApplySnapshotChunk>): _46.ResponseApplySnapshotChunk;
            fromAmino(object: _46.ResponseApplySnapshotChunkAmino): _46.ResponseApplySnapshotChunk;
            toAmino(message: _46.ResponseApplySnapshotChunk): _46.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _46.ResponseApplySnapshotChunkAminoMsg): _46.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _46.ResponseApplySnapshotChunkProtoMsg): _46.ResponseApplySnapshotChunk;
            toProto(message: _46.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _46.ResponseApplySnapshotChunk): _46.ResponseApplySnapshotChunkProtoMsg;
        };
        ResponsePrepareProposal: {
            typeUrl: string;
            encode(message: _46.ResponsePrepareProposal, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ResponsePrepareProposal;
            fromPartial(object: Partial<_46.ResponsePrepareProposal>): _46.ResponsePrepareProposal;
            fromAmino(object: _46.ResponsePrepareProposalAmino): _46.ResponsePrepareProposal;
            toAmino(message: _46.ResponsePrepareProposal): _46.ResponsePrepareProposalAmino;
            fromAminoMsg(object: _46.ResponsePrepareProposalAminoMsg): _46.ResponsePrepareProposal;
            fromProtoMsg(message: _46.ResponsePrepareProposalProtoMsg): _46.ResponsePrepareProposal;
            toProto(message: _46.ResponsePrepareProposal): Uint8Array;
            toProtoMsg(message: _46.ResponsePrepareProposal): _46.ResponsePrepareProposalProtoMsg;
        };
        ResponseProcessProposal: {
            typeUrl: string;
            encode(message: _46.ResponseProcessProposal, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ResponseProcessProposal;
            fromPartial(object: Partial<_46.ResponseProcessProposal>): _46.ResponseProcessProposal;
            fromAmino(object: _46.ResponseProcessProposalAmino): _46.ResponseProcessProposal;
            toAmino(message: _46.ResponseProcessProposal): _46.ResponseProcessProposalAmino;
            fromAminoMsg(object: _46.ResponseProcessProposalAminoMsg): _46.ResponseProcessProposal;
            fromProtoMsg(message: _46.ResponseProcessProposalProtoMsg): _46.ResponseProcessProposal;
            toProto(message: _46.ResponseProcessProposal): Uint8Array;
            toProtoMsg(message: _46.ResponseProcessProposal): _46.ResponseProcessProposalProtoMsg;
        };
        CommitInfo: {
            typeUrl: string;
            encode(message: _46.CommitInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.CommitInfo;
            fromPartial(object: Partial<_46.CommitInfo>): _46.CommitInfo;
            fromAmino(object: _46.CommitInfoAmino): _46.CommitInfo;
            toAmino(message: _46.CommitInfo): _46.CommitInfoAmino;
            fromAminoMsg(object: _46.CommitInfoAminoMsg): _46.CommitInfo;
            fromProtoMsg(message: _46.CommitInfoProtoMsg): _46.CommitInfo;
            toProto(message: _46.CommitInfo): Uint8Array;
            toProtoMsg(message: _46.CommitInfo): _46.CommitInfoProtoMsg;
        };
        ExtendedCommitInfo: {
            typeUrl: string;
            encode(message: _46.ExtendedCommitInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ExtendedCommitInfo;
            fromPartial(object: Partial<_46.ExtendedCommitInfo>): _46.ExtendedCommitInfo;
            fromAmino(object: _46.ExtendedCommitInfoAmino): _46.ExtendedCommitInfo;
            toAmino(message: _46.ExtendedCommitInfo): _46.ExtendedCommitInfoAmino;
            fromAminoMsg(object: _46.ExtendedCommitInfoAminoMsg): _46.ExtendedCommitInfo;
            fromProtoMsg(message: _46.ExtendedCommitInfoProtoMsg): _46.ExtendedCommitInfo;
            toProto(message: _46.ExtendedCommitInfo): Uint8Array;
            toProtoMsg(message: _46.ExtendedCommitInfo): _46.ExtendedCommitInfoProtoMsg;
        };
        Event: {
            typeUrl: string;
            encode(message: _46.Event, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.Event;
            fromPartial(object: Partial<_46.Event>): _46.Event;
            fromAmino(object: _46.EventAmino): _46.Event;
            toAmino(message: _46.Event): _46.EventAmino;
            fromAminoMsg(object: _46.EventAminoMsg): _46.Event;
            fromProtoMsg(message: _46.EventProtoMsg): _46.Event;
            toProto(message: _46.Event): Uint8Array;
            toProtoMsg(message: _46.Event): _46.EventProtoMsg;
        };
        EventAttribute: {
            typeUrl: string;
            encode(message: _46.EventAttribute, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.EventAttribute;
            fromPartial(object: Partial<_46.EventAttribute>): _46.EventAttribute;
            fromAmino(object: _46.EventAttributeAmino): _46.EventAttribute;
            toAmino(message: _46.EventAttribute): _46.EventAttributeAmino;
            fromAminoMsg(object: _46.EventAttributeAminoMsg): _46.EventAttribute;
            fromProtoMsg(message: _46.EventAttributeProtoMsg): _46.EventAttribute;
            toProto(message: _46.EventAttribute): Uint8Array;
            toProtoMsg(message: _46.EventAttribute): _46.EventAttributeProtoMsg;
        };
        TxResult: {
            typeUrl: string;
            encode(message: _46.TxResult, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.TxResult;
            fromPartial(object: Partial<_46.TxResult>): _46.TxResult;
            fromAmino(object: _46.TxResultAmino): _46.TxResult;
            toAmino(message: _46.TxResult): _46.TxResultAmino;
            fromAminoMsg(object: _46.TxResultAminoMsg): _46.TxResult;
            fromProtoMsg(message: _46.TxResultProtoMsg): _46.TxResult;
            toProto(message: _46.TxResult): Uint8Array;
            toProtoMsg(message: _46.TxResult): _46.TxResultProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _46.Validator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.Validator;
            fromPartial(object: Partial<_46.Validator>): _46.Validator;
            fromAmino(object: _46.ValidatorAmino): _46.Validator;
            toAmino(message: _46.Validator): _46.ValidatorAmino;
            fromAminoMsg(object: _46.ValidatorAminoMsg): _46.Validator;
            fromProtoMsg(message: _46.ValidatorProtoMsg): _46.Validator;
            toProto(message: _46.Validator): Uint8Array;
            toProtoMsg(message: _46.Validator): _46.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            typeUrl: string;
            encode(message: _46.ValidatorUpdate, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ValidatorUpdate;
            fromPartial(object: Partial<_46.ValidatorUpdate>): _46.ValidatorUpdate;
            fromAmino(object: _46.ValidatorUpdateAmino): _46.ValidatorUpdate;
            toAmino(message: _46.ValidatorUpdate): _46.ValidatorUpdateAmino;
            fromAminoMsg(object: _46.ValidatorUpdateAminoMsg): _46.ValidatorUpdate;
            fromProtoMsg(message: _46.ValidatorUpdateProtoMsg): _46.ValidatorUpdate;
            toProto(message: _46.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _46.ValidatorUpdate): _46.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            typeUrl: string;
            encode(message: _46.VoteInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.VoteInfo;
            fromPartial(object: Partial<_46.VoteInfo>): _46.VoteInfo;
            fromAmino(object: _46.VoteInfoAmino): _46.VoteInfo;
            toAmino(message: _46.VoteInfo): _46.VoteInfoAmino;
            fromAminoMsg(object: _46.VoteInfoAminoMsg): _46.VoteInfo;
            fromProtoMsg(message: _46.VoteInfoProtoMsg): _46.VoteInfo;
            toProto(message: _46.VoteInfo): Uint8Array;
            toProtoMsg(message: _46.VoteInfo): _46.VoteInfoProtoMsg;
        };
        ExtendedVoteInfo: {
            typeUrl: string;
            encode(message: _46.ExtendedVoteInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.ExtendedVoteInfo;
            fromPartial(object: Partial<_46.ExtendedVoteInfo>): _46.ExtendedVoteInfo;
            fromAmino(object: _46.ExtendedVoteInfoAmino): _46.ExtendedVoteInfo;
            toAmino(message: _46.ExtendedVoteInfo): _46.ExtendedVoteInfoAmino;
            fromAminoMsg(object: _46.ExtendedVoteInfoAminoMsg): _46.ExtendedVoteInfo;
            fromProtoMsg(message: _46.ExtendedVoteInfoProtoMsg): _46.ExtendedVoteInfo;
            toProto(message: _46.ExtendedVoteInfo): Uint8Array;
            toProtoMsg(message: _46.ExtendedVoteInfo): _46.ExtendedVoteInfoProtoMsg;
        };
        Misbehavior: {
            typeUrl: string;
            encode(message: _46.Misbehavior, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.Misbehavior;
            fromPartial(object: Partial<_46.Misbehavior>): _46.Misbehavior;
            fromAmino(object: _46.MisbehaviorAmino): _46.Misbehavior;
            toAmino(message: _46.Misbehavior): _46.MisbehaviorAmino;
            fromAminoMsg(object: _46.MisbehaviorAminoMsg): _46.Misbehavior;
            fromProtoMsg(message: _46.MisbehaviorProtoMsg): _46.Misbehavior;
            toProto(message: _46.Misbehavior): Uint8Array;
            toProtoMsg(message: _46.Misbehavior): _46.MisbehaviorProtoMsg;
        };
        Snapshot: {
            typeUrl: string;
            encode(message: _46.Snapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _46.Snapshot;
            fromPartial(object: Partial<_46.Snapshot>): _46.Snapshot;
            fromAmino(object: _46.SnapshotAmino): _46.Snapshot;
            toAmino(message: _46.Snapshot): _46.SnapshotAmino;
            fromAminoMsg(object: _46.SnapshotAminoMsg): _46.Snapshot;
            fromProtoMsg(message: _46.SnapshotProtoMsg): _46.Snapshot;
            toProto(message: _46.Snapshot): Uint8Array;
            toProtoMsg(message: _46.Snapshot): _46.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            typeUrl: string;
            encode(message: _48.Proof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _48.Proof;
            fromPartial(object: Partial<_48.Proof>): _48.Proof;
            fromAmino(object: _48.ProofAmino): _48.Proof;
            toAmino(message: _48.Proof): _48.ProofAmino;
            fromAminoMsg(object: _48.ProofAminoMsg): _48.Proof;
            fromProtoMsg(message: _48.ProofProtoMsg): _48.Proof;
            toProto(message: _48.Proof): Uint8Array;
            toProtoMsg(message: _48.Proof): _48.ProofProtoMsg;
        };
        ValueOp: {
            typeUrl: string;
            encode(message: _48.ValueOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _48.ValueOp;
            fromPartial(object: Partial<_48.ValueOp>): _48.ValueOp;
            fromAmino(object: _48.ValueOpAmino): _48.ValueOp;
            toAmino(message: _48.ValueOp): _48.ValueOpAmino;
            fromAminoMsg(object: _48.ValueOpAminoMsg): _48.ValueOp;
            fromProtoMsg(message: _48.ValueOpProtoMsg): _48.ValueOp;
            toProto(message: _48.ValueOp): Uint8Array;
            toProtoMsg(message: _48.ValueOp): _48.ValueOpProtoMsg;
        };
        DominoOp: {
            typeUrl: string;
            encode(message: _48.DominoOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _48.DominoOp;
            fromPartial(object: Partial<_48.DominoOp>): _48.DominoOp;
            fromAmino(object: _48.DominoOpAmino): _48.DominoOp;
            toAmino(message: _48.DominoOp): _48.DominoOpAmino;
            fromAminoMsg(object: _48.DominoOpAminoMsg): _48.DominoOp;
            fromProtoMsg(message: _48.DominoOpProtoMsg): _48.DominoOp;
            toProto(message: _48.DominoOp): Uint8Array;
            toProtoMsg(message: _48.DominoOp): _48.DominoOpProtoMsg;
        };
        ProofOp: {
            typeUrl: string;
            encode(message: _48.ProofOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _48.ProofOp;
            fromPartial(object: Partial<_48.ProofOp>): _48.ProofOp;
            fromAmino(object: _48.ProofOpAmino): _48.ProofOp;
            toAmino(message: _48.ProofOp): _48.ProofOpAmino;
            fromAminoMsg(object: _48.ProofOpAminoMsg): _48.ProofOp;
            fromProtoMsg(message: _48.ProofOpProtoMsg): _48.ProofOp;
            toProto(message: _48.ProofOp): Uint8Array;
            toProtoMsg(message: _48.ProofOp): _48.ProofOpProtoMsg;
        };
        ProofOps: {
            typeUrl: string;
            encode(message: _48.ProofOps, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _48.ProofOps;
            fromPartial(object: Partial<_48.ProofOps>): _48.ProofOps;
            fromAmino(object: _48.ProofOpsAmino): _48.ProofOps;
            toAmino(message: _48.ProofOps): _48.ProofOpsAmino;
            fromAminoMsg(object: _48.ProofOpsAminoMsg): _48.ProofOps;
            fromProtoMsg(message: _48.ProofOpsProtoMsg): _48.ProofOps;
            toProto(message: _48.ProofOps): Uint8Array;
            toProtoMsg(message: _48.ProofOps): _48.ProofOpsProtoMsg;
        };
        PublicKey: {
            typeUrl: string;
            encode(message: _47.PublicKey, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _47.PublicKey;
            fromPartial(object: Partial<_47.PublicKey>): _47.PublicKey;
            fromAmino(object: _47.PublicKeyAmino): _47.PublicKey;
            toAmino(message: _47.PublicKey): _47.PublicKeyAmino;
            fromAminoMsg(object: _47.PublicKeyAminoMsg): _47.PublicKey;
            fromProtoMsg(message: _47.PublicKeyProtoMsg): _47.PublicKey;
            toProto(message: _47.PublicKey): Uint8Array;
            toProtoMsg(message: _47.PublicKey): _47.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                typeUrl: string;
                encode(message: _49.BitArray, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
                decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _49.BitArray;
                fromPartial(object: Partial<_49.BitArray>): _49.BitArray;
                fromAmino(object: _49.BitArrayAmino): _49.BitArray;
                toAmino(message: _49.BitArray): _49.BitArrayAmino;
                fromAminoMsg(object: _49.BitArrayAminoMsg): _49.BitArray;
                fromProtoMsg(message: _49.BitArrayProtoMsg): _49.BitArray;
                toProto(message: _49.BitArray): Uint8Array;
                toProtoMsg(message: _49.BitArray): _49.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            typeUrl: string;
            encode(message: _50.NetAddress, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _50.NetAddress;
            fromPartial(object: Partial<_50.NetAddress>): _50.NetAddress;
            fromAmino(object: _50.NetAddressAmino): _50.NetAddress;
            toAmino(message: _50.NetAddress): _50.NetAddressAmino;
            fromAminoMsg(object: _50.NetAddressAminoMsg): _50.NetAddress;
            fromProtoMsg(message: _50.NetAddressProtoMsg): _50.NetAddress;
            toProto(message: _50.NetAddress): Uint8Array;
            toProtoMsg(message: _50.NetAddress): _50.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            typeUrl: string;
            encode(message: _50.ProtocolVersion, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _50.ProtocolVersion;
            fromPartial(object: Partial<_50.ProtocolVersion>): _50.ProtocolVersion;
            fromAmino(object: _50.ProtocolVersionAmino): _50.ProtocolVersion;
            toAmino(message: _50.ProtocolVersion): _50.ProtocolVersionAmino;
            fromAminoMsg(object: _50.ProtocolVersionAminoMsg): _50.ProtocolVersion;
            fromProtoMsg(message: _50.ProtocolVersionProtoMsg): _50.ProtocolVersion;
            toProto(message: _50.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _50.ProtocolVersion): _50.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            typeUrl: string;
            encode(message: _50.DefaultNodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _50.DefaultNodeInfo;
            fromPartial(object: Partial<_50.DefaultNodeInfo>): _50.DefaultNodeInfo;
            fromAmino(object: _50.DefaultNodeInfoAmino): _50.DefaultNodeInfo;
            toAmino(message: _50.DefaultNodeInfo): _50.DefaultNodeInfoAmino;
            fromAminoMsg(object: _50.DefaultNodeInfoAminoMsg): _50.DefaultNodeInfo;
            fromProtoMsg(message: _50.DefaultNodeInfoProtoMsg): _50.DefaultNodeInfo;
            toProto(message: _50.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _50.DefaultNodeInfo): _50.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            typeUrl: string;
            encode(message: _50.DefaultNodeInfoOther, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _50.DefaultNodeInfoOther;
            fromPartial(object: Partial<_50.DefaultNodeInfoOther>): _50.DefaultNodeInfoOther;
            fromAmino(object: _50.DefaultNodeInfoOtherAmino): _50.DefaultNodeInfoOther;
            toAmino(message: _50.DefaultNodeInfoOther): _50.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _50.DefaultNodeInfoOtherAminoMsg): _50.DefaultNodeInfoOther;
            fromProtoMsg(message: _50.DefaultNodeInfoOtherProtoMsg): _50.DefaultNodeInfoOther;
            toProto(message: _50.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _50.DefaultNodeInfoOther): _50.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            typeUrl: string;
            encode(message: _55.ValidatorSet, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _55.ValidatorSet;
            fromPartial(object: Partial<_55.ValidatorSet>): _55.ValidatorSet;
            fromAmino(object: _55.ValidatorSetAmino): _55.ValidatorSet;
            toAmino(message: _55.ValidatorSet): _55.ValidatorSetAmino;
            fromAminoMsg(object: _55.ValidatorSetAminoMsg): _55.ValidatorSet;
            fromProtoMsg(message: _55.ValidatorSetProtoMsg): _55.ValidatorSet;
            toProto(message: _55.ValidatorSet): Uint8Array;
            toProtoMsg(message: _55.ValidatorSet): _55.ValidatorSetProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _55.Validator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _55.Validator;
            fromPartial(object: Partial<_55.Validator>): _55.Validator;
            fromAmino(object: _55.ValidatorAmino): _55.Validator;
            toAmino(message: _55.Validator): _55.ValidatorAmino;
            fromAminoMsg(object: _55.ValidatorAminoMsg): _55.Validator;
            fromProtoMsg(message: _55.ValidatorProtoMsg): _55.Validator;
            toProto(message: _55.Validator): Uint8Array;
            toProtoMsg(message: _55.Validator): _55.ValidatorProtoMsg;
        };
        SimpleValidator: {
            typeUrl: string;
            encode(message: _55.SimpleValidator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _55.SimpleValidator;
            fromPartial(object: Partial<_55.SimpleValidator>): _55.SimpleValidator;
            fromAmino(object: _55.SimpleValidatorAmino): _55.SimpleValidator;
            toAmino(message: _55.SimpleValidator): _55.SimpleValidatorAmino;
            fromAminoMsg(object: _55.SimpleValidatorAminoMsg): _55.SimpleValidator;
            fromProtoMsg(message: _55.SimpleValidatorProtoMsg): _55.SimpleValidator;
            toProto(message: _55.SimpleValidator): Uint8Array;
            toProtoMsg(message: _55.SimpleValidator): _55.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _54.BlockIDFlag;
        blockIDFlagToJSON(object: _54.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _54.SignedMsgType;
        signedMsgTypeToJSON(object: _54.SignedMsgType): string;
        BlockIDFlag: typeof _54.BlockIDFlag;
        BlockIDFlagSDKType: typeof _54.BlockIDFlag;
        BlockIDFlagAmino: typeof _54.BlockIDFlag;
        SignedMsgType: typeof _54.SignedMsgType;
        SignedMsgTypeSDKType: typeof _54.SignedMsgType;
        SignedMsgTypeAmino: typeof _54.SignedMsgType;
        PartSetHeader: {
            typeUrl: string;
            encode(message: _54.PartSetHeader, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.PartSetHeader;
            fromPartial(object: Partial<_54.PartSetHeader>): _54.PartSetHeader;
            fromAmino(object: _54.PartSetHeaderAmino): _54.PartSetHeader;
            toAmino(message: _54.PartSetHeader): _54.PartSetHeaderAmino;
            fromAminoMsg(object: _54.PartSetHeaderAminoMsg): _54.PartSetHeader;
            fromProtoMsg(message: _54.PartSetHeaderProtoMsg): _54.PartSetHeader;
            toProto(message: _54.PartSetHeader): Uint8Array;
            toProtoMsg(message: _54.PartSetHeader): _54.PartSetHeaderProtoMsg;
        };
        Part: {
            typeUrl: string;
            encode(message: _54.Part, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.Part;
            fromPartial(object: Partial<_54.Part>): _54.Part;
            fromAmino(object: _54.PartAmino): _54.Part;
            toAmino(message: _54.Part): _54.PartAmino;
            fromAminoMsg(object: _54.PartAminoMsg): _54.Part;
            fromProtoMsg(message: _54.PartProtoMsg): _54.Part;
            toProto(message: _54.Part): Uint8Array;
            toProtoMsg(message: _54.Part): _54.PartProtoMsg;
        };
        BlockID: {
            typeUrl: string;
            encode(message: _54.BlockID, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.BlockID;
            fromPartial(object: Partial<_54.BlockID>): _54.BlockID;
            fromAmino(object: _54.BlockIDAmino): _54.BlockID;
            toAmino(message: _54.BlockID): _54.BlockIDAmino;
            fromAminoMsg(object: _54.BlockIDAminoMsg): _54.BlockID;
            fromProtoMsg(message: _54.BlockIDProtoMsg): _54.BlockID;
            toProto(message: _54.BlockID): Uint8Array;
            toProtoMsg(message: _54.BlockID): _54.BlockIDProtoMsg;
        };
        Header: {
            typeUrl: string;
            encode(message: _54.Header, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.Header;
            fromPartial(object: Partial<_54.Header>): _54.Header;
            fromAmino(object: _54.HeaderAmino): _54.Header;
            toAmino(message: _54.Header): _54.HeaderAmino;
            fromAminoMsg(object: _54.HeaderAminoMsg): _54.Header;
            fromProtoMsg(message: _54.HeaderProtoMsg): _54.Header;
            toProto(message: _54.Header): Uint8Array;
            toProtoMsg(message: _54.Header): _54.HeaderProtoMsg;
        };
        Data: {
            typeUrl: string;
            encode(message: _54.Data, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.Data;
            fromPartial(object: Partial<_54.Data>): _54.Data;
            fromAmino(object: _54.DataAmino): _54.Data;
            toAmino(message: _54.Data): _54.DataAmino;
            fromAminoMsg(object: _54.DataAminoMsg): _54.Data;
            fromProtoMsg(message: _54.DataProtoMsg): _54.Data;
            toProto(message: _54.Data): Uint8Array;
            toProtoMsg(message: _54.Data): _54.DataProtoMsg;
        };
        Vote: {
            typeUrl: string;
            encode(message: _54.Vote, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.Vote;
            fromPartial(object: Partial<_54.Vote>): _54.Vote;
            fromAmino(object: _54.VoteAmino): _54.Vote;
            toAmino(message: _54.Vote): _54.VoteAmino;
            fromAminoMsg(object: _54.VoteAminoMsg): _54.Vote;
            fromProtoMsg(message: _54.VoteProtoMsg): _54.Vote;
            toProto(message: _54.Vote): Uint8Array;
            toProtoMsg(message: _54.Vote): _54.VoteProtoMsg;
        };
        Commit: {
            typeUrl: string;
            encode(message: _54.Commit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.Commit;
            fromPartial(object: Partial<_54.Commit>): _54.Commit;
            fromAmino(object: _54.CommitAmino): _54.Commit;
            toAmino(message: _54.Commit): _54.CommitAmino;
            fromAminoMsg(object: _54.CommitAminoMsg): _54.Commit;
            fromProtoMsg(message: _54.CommitProtoMsg): _54.Commit;
            toProto(message: _54.Commit): Uint8Array;
            toProtoMsg(message: _54.Commit): _54.CommitProtoMsg;
        };
        CommitSig: {
            typeUrl: string;
            encode(message: _54.CommitSig, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.CommitSig;
            fromPartial(object: Partial<_54.CommitSig>): _54.CommitSig;
            fromAmino(object: _54.CommitSigAmino): _54.CommitSig;
            toAmino(message: _54.CommitSig): _54.CommitSigAmino;
            fromAminoMsg(object: _54.CommitSigAminoMsg): _54.CommitSig;
            fromProtoMsg(message: _54.CommitSigProtoMsg): _54.CommitSig;
            toProto(message: _54.CommitSig): Uint8Array;
            toProtoMsg(message: _54.CommitSig): _54.CommitSigProtoMsg;
        };
        Proposal: {
            typeUrl: string;
            encode(message: _54.Proposal, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.Proposal;
            fromPartial(object: Partial<_54.Proposal>): _54.Proposal;
            fromAmino(object: _54.ProposalAmino): _54.Proposal;
            toAmino(message: _54.Proposal): _54.ProposalAmino;
            fromAminoMsg(object: _54.ProposalAminoMsg): _54.Proposal;
            fromProtoMsg(message: _54.ProposalProtoMsg): _54.Proposal;
            toProto(message: _54.Proposal): Uint8Array;
            toProtoMsg(message: _54.Proposal): _54.ProposalProtoMsg;
        };
        SignedHeader: {
            typeUrl: string;
            encode(message: _54.SignedHeader, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.SignedHeader;
            fromPartial(object: Partial<_54.SignedHeader>): _54.SignedHeader;
            fromAmino(object: _54.SignedHeaderAmino): _54.SignedHeader;
            toAmino(message: _54.SignedHeader): _54.SignedHeaderAmino;
            fromAminoMsg(object: _54.SignedHeaderAminoMsg): _54.SignedHeader;
            fromProtoMsg(message: _54.SignedHeaderProtoMsg): _54.SignedHeader;
            toProto(message: _54.SignedHeader): Uint8Array;
            toProtoMsg(message: _54.SignedHeader): _54.SignedHeaderProtoMsg;
        };
        LightBlock: {
            typeUrl: string;
            encode(message: _54.LightBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.LightBlock;
            fromPartial(object: Partial<_54.LightBlock>): _54.LightBlock;
            fromAmino(object: _54.LightBlockAmino): _54.LightBlock;
            toAmino(message: _54.LightBlock): _54.LightBlockAmino;
            fromAminoMsg(object: _54.LightBlockAminoMsg): _54.LightBlock;
            fromProtoMsg(message: _54.LightBlockProtoMsg): _54.LightBlock;
            toProto(message: _54.LightBlock): Uint8Array;
            toProtoMsg(message: _54.LightBlock): _54.LightBlockProtoMsg;
        };
        BlockMeta: {
            typeUrl: string;
            encode(message: _54.BlockMeta, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.BlockMeta;
            fromPartial(object: Partial<_54.BlockMeta>): _54.BlockMeta;
            fromAmino(object: _54.BlockMetaAmino): _54.BlockMeta;
            toAmino(message: _54.BlockMeta): _54.BlockMetaAmino;
            fromAminoMsg(object: _54.BlockMetaAminoMsg): _54.BlockMeta;
            fromProtoMsg(message: _54.BlockMetaProtoMsg): _54.BlockMeta;
            toProto(message: _54.BlockMeta): Uint8Array;
            toProtoMsg(message: _54.BlockMeta): _54.BlockMetaProtoMsg;
        };
        TxProof: {
            typeUrl: string;
            encode(message: _54.TxProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.TxProof;
            fromPartial(object: Partial<_54.TxProof>): _54.TxProof;
            fromAmino(object: _54.TxProofAmino): _54.TxProof;
            toAmino(message: _54.TxProof): _54.TxProofAmino;
            fromAminoMsg(object: _54.TxProofAminoMsg): _54.TxProof;
            fromProtoMsg(message: _54.TxProofProtoMsg): _54.TxProof;
            toProto(message: _54.TxProof): Uint8Array;
            toProtoMsg(message: _54.TxProof): _54.TxProofProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _53.ConsensusParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _53.ConsensusParams;
            fromPartial(object: Partial<_53.ConsensusParams>): _53.ConsensusParams;
            fromAmino(object: _53.ConsensusParamsAmino): _53.ConsensusParams;
            toAmino(message: _53.ConsensusParams): _53.ConsensusParamsAmino;
            fromAminoMsg(object: _53.ConsensusParamsAminoMsg): _53.ConsensusParams;
            fromProtoMsg(message: _53.ConsensusParamsProtoMsg): _53.ConsensusParams;
            toProto(message: _53.ConsensusParams): Uint8Array;
            toProtoMsg(message: _53.ConsensusParams): _53.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _53.BlockParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _53.BlockParams;
            fromPartial(object: Partial<_53.BlockParams>): _53.BlockParams;
            fromAmino(object: _53.BlockParamsAmino): _53.BlockParams;
            toAmino(message: _53.BlockParams): _53.BlockParamsAmino;
            fromAminoMsg(object: _53.BlockParamsAminoMsg): _53.BlockParams;
            fromProtoMsg(message: _53.BlockParamsProtoMsg): _53.BlockParams;
            toProto(message: _53.BlockParams): Uint8Array;
            toProtoMsg(message: _53.BlockParams): _53.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            typeUrl: string;
            encode(message: _53.EvidenceParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _53.EvidenceParams;
            fromPartial(object: Partial<_53.EvidenceParams>): _53.EvidenceParams;
            fromAmino(object: _53.EvidenceParamsAmino): _53.EvidenceParams;
            toAmino(message: _53.EvidenceParams): _53.EvidenceParamsAmino;
            fromAminoMsg(object: _53.EvidenceParamsAminoMsg): _53.EvidenceParams;
            fromProtoMsg(message: _53.EvidenceParamsProtoMsg): _53.EvidenceParams;
            toProto(message: _53.EvidenceParams): Uint8Array;
            toProtoMsg(message: _53.EvidenceParams): _53.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            typeUrl: string;
            encode(message: _53.ValidatorParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _53.ValidatorParams;
            fromPartial(object: Partial<_53.ValidatorParams>): _53.ValidatorParams;
            fromAmino(object: _53.ValidatorParamsAmino): _53.ValidatorParams;
            toAmino(message: _53.ValidatorParams): _53.ValidatorParamsAmino;
            fromAminoMsg(object: _53.ValidatorParamsAminoMsg): _53.ValidatorParams;
            fromProtoMsg(message: _53.ValidatorParamsProtoMsg): _53.ValidatorParams;
            toProto(message: _53.ValidatorParams): Uint8Array;
            toProtoMsg(message: _53.ValidatorParams): _53.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            typeUrl: string;
            encode(message: _53.VersionParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _53.VersionParams;
            fromPartial(object: Partial<_53.VersionParams>): _53.VersionParams;
            fromAmino(object: _53.VersionParamsAmino): _53.VersionParams;
            toAmino(message: _53.VersionParams): _53.VersionParamsAmino;
            fromAminoMsg(object: _53.VersionParamsAminoMsg): _53.VersionParams;
            fromProtoMsg(message: _53.VersionParamsProtoMsg): _53.VersionParams;
            toProto(message: _53.VersionParams): Uint8Array;
            toProtoMsg(message: _53.VersionParams): _53.VersionParamsProtoMsg;
        };
        HashedParams: {
            typeUrl: string;
            encode(message: _53.HashedParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _53.HashedParams;
            fromPartial(object: Partial<_53.HashedParams>): _53.HashedParams;
            fromAmino(object: _53.HashedParamsAmino): _53.HashedParams;
            toAmino(message: _53.HashedParams): _53.HashedParamsAmino;
            fromAminoMsg(object: _53.HashedParamsAminoMsg): _53.HashedParams;
            fromProtoMsg(message: _53.HashedParamsProtoMsg): _53.HashedParams;
            toProto(message: _53.HashedParams): Uint8Array;
            toProtoMsg(message: _53.HashedParams): _53.HashedParamsProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _52.Evidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _52.Evidence;
            fromPartial(object: Partial<_52.Evidence>): _52.Evidence;
            fromAmino(object: _52.EvidenceAmino): _52.Evidence;
            toAmino(message: _52.Evidence): _52.EvidenceAmino;
            fromAminoMsg(object: _52.EvidenceAminoMsg): _52.Evidence;
            fromProtoMsg(message: _52.EvidenceProtoMsg): _52.Evidence;
            toProto(message: _52.Evidence): Uint8Array;
            toProtoMsg(message: _52.Evidence): _52.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            typeUrl: string;
            encode(message: _52.DuplicateVoteEvidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _52.DuplicateVoteEvidence;
            fromPartial(object: Partial<_52.DuplicateVoteEvidence>): _52.DuplicateVoteEvidence;
            fromAmino(object: _52.DuplicateVoteEvidenceAmino): _52.DuplicateVoteEvidence;
            toAmino(message: _52.DuplicateVoteEvidence): _52.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _52.DuplicateVoteEvidenceAminoMsg): _52.DuplicateVoteEvidence;
            fromProtoMsg(message: _52.DuplicateVoteEvidenceProtoMsg): _52.DuplicateVoteEvidence;
            toProto(message: _52.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _52.DuplicateVoteEvidence): _52.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            typeUrl: string;
            encode(message: _52.LightClientAttackEvidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _52.LightClientAttackEvidence;
            fromPartial(object: Partial<_52.LightClientAttackEvidence>): _52.LightClientAttackEvidence;
            fromAmino(object: _52.LightClientAttackEvidenceAmino): _52.LightClientAttackEvidence;
            toAmino(message: _52.LightClientAttackEvidence): _52.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _52.LightClientAttackEvidenceAminoMsg): _52.LightClientAttackEvidence;
            fromProtoMsg(message: _52.LightClientAttackEvidenceProtoMsg): _52.LightClientAttackEvidence;
            toProto(message: _52.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _52.LightClientAttackEvidence): _52.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            typeUrl: string;
            encode(message: _52.EvidenceList, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _52.EvidenceList;
            fromPartial(object: Partial<_52.EvidenceList>): _52.EvidenceList;
            fromAmino(object: _52.EvidenceListAmino): _52.EvidenceList;
            toAmino(message: _52.EvidenceList): _52.EvidenceListAmino;
            fromAminoMsg(object: _52.EvidenceListAminoMsg): _52.EvidenceList;
            fromProtoMsg(message: _52.EvidenceListProtoMsg): _52.EvidenceList;
            toProto(message: _52.EvidenceList): Uint8Array;
            toProtoMsg(message: _52.EvidenceList): _52.EvidenceListProtoMsg;
        };
        Block: {
            typeUrl: string;
            encode(message: _51.Block, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _51.Block;
            fromPartial(object: Partial<_51.Block>): _51.Block;
            fromAmino(object: _51.BlockAmino): _51.Block;
            toAmino(message: _51.Block): _51.BlockAmino;
            fromAminoMsg(object: _51.BlockAminoMsg): _51.Block;
            fromProtoMsg(message: _51.BlockProtoMsg): _51.Block;
            toProto(message: _51.Block): Uint8Array;
            toProtoMsg(message: _51.Block): _51.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            typeUrl: string;
            encode(message: _56.App, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _56.App;
            fromPartial(object: Partial<_56.App>): _56.App;
            fromAmino(object: _56.AppAmino): _56.App;
            toAmino(message: _56.App): _56.AppAmino;
            fromAminoMsg(object: _56.AppAminoMsg): _56.App;
            fromProtoMsg(message: _56.AppProtoMsg): _56.App;
            toProto(message: _56.App): Uint8Array;
            toProtoMsg(message: _56.App): _56.AppProtoMsg;
        };
        Consensus: {
            typeUrl: string;
            encode(message: _56.Consensus, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _56.Consensus;
            fromPartial(object: Partial<_56.Consensus>): _56.Consensus;
            fromAmino(object: _56.ConsensusAmino): _56.Consensus;
            toAmino(message: _56.Consensus): _56.ConsensusAmino;
            fromAminoMsg(object: _56.ConsensusAminoMsg): _56.Consensus;
            fromProtoMsg(message: _56.ConsensusProtoMsg): _56.Consensus;
            toProto(message: _56.Consensus): Uint8Array;
            toProtoMsg(message: _56.Consensus): _56.ConsensusProtoMsg;
        };
    };
}
