import * as _75 from "./abci/types";
import * as _76 from "./crypto/keys";
import * as _77 from "./crypto/proof";
import * as _78 from "./libs/bits/types";
import * as _79 from "./p2p/types";
import * as _80 from "./types/block";
import * as _81 from "./types/evidence";
import * as _82 from "./types/params";
import * as _83 from "./types/types";
import * as _84 from "./types/validator";
import * as _85 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _75.CheckTxType;
        checkTxTypeToJSON(object: _75.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _75.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _75.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _75.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _75.ResponseApplySnapshotChunk_Result): string;
        evidenceTypeFromJSON(object: any): _75.EvidenceType;
        evidenceTypeToJSON(object: _75.EvidenceType): string;
        CheckTxType: typeof _75.CheckTxType;
        CheckTxTypeSDKType: typeof _75.CheckTxType;
        CheckTxTypeAmino: typeof _75.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _75.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _75.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _75.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _75.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _75.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _75.ResponseApplySnapshotChunk_Result;
        EvidenceType: typeof _75.EvidenceType;
        EvidenceTypeSDKType: typeof _75.EvidenceType;
        EvidenceTypeAmino: typeof _75.EvidenceType;
        Request: {
            encode(message: _75.Request, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.Request;
            fromPartial(object: Partial<_75.Request>): _75.Request;
            fromAmino(object: _75.RequestAmino): _75.Request;
            toAmino(message: _75.Request): _75.RequestAmino;
            fromAminoMsg(object: _75.RequestAminoMsg): _75.Request;
            fromProtoMsg(message: _75.RequestProtoMsg): _75.Request;
            toProto(message: _75.Request): Uint8Array;
            toProtoMsg(message: _75.Request): _75.RequestProtoMsg;
        };
        RequestEcho: {
            encode(message: _75.RequestEcho, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.RequestEcho;
            fromPartial(object: Partial<_75.RequestEcho>): _75.RequestEcho;
            fromAmino(object: _75.RequestEchoAmino): _75.RequestEcho;
            toAmino(message: _75.RequestEcho): _75.RequestEchoAmino;
            fromAminoMsg(object: _75.RequestEchoAminoMsg): _75.RequestEcho;
            fromProtoMsg(message: _75.RequestEchoProtoMsg): _75.RequestEcho;
            toProto(message: _75.RequestEcho): Uint8Array;
            toProtoMsg(message: _75.RequestEcho): _75.RequestEchoProtoMsg;
        };
        RequestFlush: {
            encode(_: _75.RequestFlush, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.RequestFlush;
            fromPartial(_: Partial<_75.RequestFlush>): _75.RequestFlush;
            fromAmino(_: _75.RequestFlushAmino): _75.RequestFlush;
            toAmino(_: _75.RequestFlush): _75.RequestFlushAmino;
            fromAminoMsg(object: _75.RequestFlushAminoMsg): _75.RequestFlush;
            fromProtoMsg(message: _75.RequestFlushProtoMsg): _75.RequestFlush;
            toProto(message: _75.RequestFlush): Uint8Array;
            toProtoMsg(message: _75.RequestFlush): _75.RequestFlushProtoMsg;
        };
        RequestInfo: {
            encode(message: _75.RequestInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.RequestInfo;
            fromPartial(object: Partial<_75.RequestInfo>): _75.RequestInfo;
            fromAmino(object: _75.RequestInfoAmino): _75.RequestInfo;
            toAmino(message: _75.RequestInfo): _75.RequestInfoAmino;
            fromAminoMsg(object: _75.RequestInfoAminoMsg): _75.RequestInfo;
            fromProtoMsg(message: _75.RequestInfoProtoMsg): _75.RequestInfo;
            toProto(message: _75.RequestInfo): Uint8Array;
            toProtoMsg(message: _75.RequestInfo): _75.RequestInfoProtoMsg;
        };
        RequestSetOption: {
            encode(message: _75.RequestSetOption, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.RequestSetOption;
            fromPartial(object: Partial<_75.RequestSetOption>): _75.RequestSetOption;
            fromAmino(object: _75.RequestSetOptionAmino): _75.RequestSetOption;
            toAmino(message: _75.RequestSetOption): _75.RequestSetOptionAmino;
            fromAminoMsg(object: _75.RequestSetOptionAminoMsg): _75.RequestSetOption;
            fromProtoMsg(message: _75.RequestSetOptionProtoMsg): _75.RequestSetOption;
            toProto(message: _75.RequestSetOption): Uint8Array;
            toProtoMsg(message: _75.RequestSetOption): _75.RequestSetOptionProtoMsg;
        };
        RequestInitChain: {
            encode(message: _75.RequestInitChain, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.RequestInitChain;
            fromPartial(object: Partial<_75.RequestInitChain>): _75.RequestInitChain;
            fromAmino(object: _75.RequestInitChainAmino): _75.RequestInitChain;
            toAmino(message: _75.RequestInitChain): _75.RequestInitChainAmino;
            fromAminoMsg(object: _75.RequestInitChainAminoMsg): _75.RequestInitChain;
            fromProtoMsg(message: _75.RequestInitChainProtoMsg): _75.RequestInitChain;
            toProto(message: _75.RequestInitChain): Uint8Array;
            toProtoMsg(message: _75.RequestInitChain): _75.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            encode(message: _75.RequestQuery, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.RequestQuery;
            fromPartial(object: Partial<_75.RequestQuery>): _75.RequestQuery;
            fromAmino(object: _75.RequestQueryAmino): _75.RequestQuery;
            toAmino(message: _75.RequestQuery): _75.RequestQueryAmino;
            fromAminoMsg(object: _75.RequestQueryAminoMsg): _75.RequestQuery;
            fromProtoMsg(message: _75.RequestQueryProtoMsg): _75.RequestQuery;
            toProto(message: _75.RequestQuery): Uint8Array;
            toProtoMsg(message: _75.RequestQuery): _75.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            encode(message: _75.RequestBeginBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.RequestBeginBlock;
            fromPartial(object: Partial<_75.RequestBeginBlock>): _75.RequestBeginBlock;
            fromAmino(object: _75.RequestBeginBlockAmino): _75.RequestBeginBlock;
            toAmino(message: _75.RequestBeginBlock): _75.RequestBeginBlockAmino;
            fromAminoMsg(object: _75.RequestBeginBlockAminoMsg): _75.RequestBeginBlock;
            fromProtoMsg(message: _75.RequestBeginBlockProtoMsg): _75.RequestBeginBlock;
            toProto(message: _75.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _75.RequestBeginBlock): _75.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            encode(message: _75.RequestCheckTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.RequestCheckTx;
            fromPartial(object: Partial<_75.RequestCheckTx>): _75.RequestCheckTx;
            fromAmino(object: _75.RequestCheckTxAmino): _75.RequestCheckTx;
            toAmino(message: _75.RequestCheckTx): _75.RequestCheckTxAmino;
            fromAminoMsg(object: _75.RequestCheckTxAminoMsg): _75.RequestCheckTx;
            fromProtoMsg(message: _75.RequestCheckTxProtoMsg): _75.RequestCheckTx;
            toProto(message: _75.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _75.RequestCheckTx): _75.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            encode(message: _75.RequestDeliverTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.RequestDeliverTx;
            fromPartial(object: Partial<_75.RequestDeliverTx>): _75.RequestDeliverTx;
            fromAmino(object: _75.RequestDeliverTxAmino): _75.RequestDeliverTx;
            toAmino(message: _75.RequestDeliverTx): _75.RequestDeliverTxAmino;
            fromAminoMsg(object: _75.RequestDeliverTxAminoMsg): _75.RequestDeliverTx;
            fromProtoMsg(message: _75.RequestDeliverTxProtoMsg): _75.RequestDeliverTx;
            toProto(message: _75.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _75.RequestDeliverTx): _75.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            encode(message: _75.RequestEndBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.RequestEndBlock;
            fromPartial(object: Partial<_75.RequestEndBlock>): _75.RequestEndBlock;
            fromAmino(object: _75.RequestEndBlockAmino): _75.RequestEndBlock;
            toAmino(message: _75.RequestEndBlock): _75.RequestEndBlockAmino;
            fromAminoMsg(object: _75.RequestEndBlockAminoMsg): _75.RequestEndBlock;
            fromProtoMsg(message: _75.RequestEndBlockProtoMsg): _75.RequestEndBlock;
            toProto(message: _75.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _75.RequestEndBlock): _75.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            encode(_: _75.RequestCommit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.RequestCommit;
            fromPartial(_: Partial<_75.RequestCommit>): _75.RequestCommit;
            fromAmino(_: _75.RequestCommitAmino): _75.RequestCommit;
            toAmino(_: _75.RequestCommit): _75.RequestCommitAmino;
            fromAminoMsg(object: _75.RequestCommitAminoMsg): _75.RequestCommit;
            fromProtoMsg(message: _75.RequestCommitProtoMsg): _75.RequestCommit;
            toProto(message: _75.RequestCommit): Uint8Array;
            toProtoMsg(message: _75.RequestCommit): _75.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            encode(_: _75.RequestListSnapshots, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.RequestListSnapshots;
            fromPartial(_: Partial<_75.RequestListSnapshots>): _75.RequestListSnapshots;
            fromAmino(_: _75.RequestListSnapshotsAmino): _75.RequestListSnapshots;
            toAmino(_: _75.RequestListSnapshots): _75.RequestListSnapshotsAmino;
            fromAminoMsg(object: _75.RequestListSnapshotsAminoMsg): _75.RequestListSnapshots;
            fromProtoMsg(message: _75.RequestListSnapshotsProtoMsg): _75.RequestListSnapshots;
            toProto(message: _75.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _75.RequestListSnapshots): _75.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            encode(message: _75.RequestOfferSnapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.RequestOfferSnapshot;
            fromPartial(object: Partial<_75.RequestOfferSnapshot>): _75.RequestOfferSnapshot;
            fromAmino(object: _75.RequestOfferSnapshotAmino): _75.RequestOfferSnapshot;
            toAmino(message: _75.RequestOfferSnapshot): _75.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _75.RequestOfferSnapshotAminoMsg): _75.RequestOfferSnapshot;
            fromProtoMsg(message: _75.RequestOfferSnapshotProtoMsg): _75.RequestOfferSnapshot;
            toProto(message: _75.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _75.RequestOfferSnapshot): _75.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            encode(message: _75.RequestLoadSnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.RequestLoadSnapshotChunk;
            fromPartial(object: Partial<_75.RequestLoadSnapshotChunk>): _75.RequestLoadSnapshotChunk;
            fromAmino(object: _75.RequestLoadSnapshotChunkAmino): _75.RequestLoadSnapshotChunk;
            toAmino(message: _75.RequestLoadSnapshotChunk): _75.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _75.RequestLoadSnapshotChunkAminoMsg): _75.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _75.RequestLoadSnapshotChunkProtoMsg): _75.RequestLoadSnapshotChunk;
            toProto(message: _75.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _75.RequestLoadSnapshotChunk): _75.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            encode(message: _75.RequestApplySnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.RequestApplySnapshotChunk;
            fromPartial(object: Partial<_75.RequestApplySnapshotChunk>): _75.RequestApplySnapshotChunk;
            fromAmino(object: _75.RequestApplySnapshotChunkAmino): _75.RequestApplySnapshotChunk;
            toAmino(message: _75.RequestApplySnapshotChunk): _75.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _75.RequestApplySnapshotChunkAminoMsg): _75.RequestApplySnapshotChunk;
            fromProtoMsg(message: _75.RequestApplySnapshotChunkProtoMsg): _75.RequestApplySnapshotChunk;
            toProto(message: _75.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _75.RequestApplySnapshotChunk): _75.RequestApplySnapshotChunkProtoMsg;
        };
        Response: {
            encode(message: _75.Response, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.Response;
            fromPartial(object: Partial<_75.Response>): _75.Response;
            fromAmino(object: _75.ResponseAmino): _75.Response;
            toAmino(message: _75.Response): _75.ResponseAmino;
            fromAminoMsg(object: _75.ResponseAminoMsg): _75.Response;
            fromProtoMsg(message: _75.ResponseProtoMsg): _75.Response;
            toProto(message: _75.Response): Uint8Array;
            toProtoMsg(message: _75.Response): _75.ResponseProtoMsg;
        };
        ResponseException: {
            encode(message: _75.ResponseException, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.ResponseException;
            fromPartial(object: Partial<_75.ResponseException>): _75.ResponseException;
            fromAmino(object: _75.ResponseExceptionAmino): _75.ResponseException;
            toAmino(message: _75.ResponseException): _75.ResponseExceptionAmino;
            fromAminoMsg(object: _75.ResponseExceptionAminoMsg): _75.ResponseException;
            fromProtoMsg(message: _75.ResponseExceptionProtoMsg): _75.ResponseException;
            toProto(message: _75.ResponseException): Uint8Array;
            toProtoMsg(message: _75.ResponseException): _75.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            encode(message: _75.ResponseEcho, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.ResponseEcho;
            fromPartial(object: Partial<_75.ResponseEcho>): _75.ResponseEcho;
            fromAmino(object: _75.ResponseEchoAmino): _75.ResponseEcho;
            toAmino(message: _75.ResponseEcho): _75.ResponseEchoAmino;
            fromAminoMsg(object: _75.ResponseEchoAminoMsg): _75.ResponseEcho;
            fromProtoMsg(message: _75.ResponseEchoProtoMsg): _75.ResponseEcho;
            toProto(message: _75.ResponseEcho): Uint8Array;
            toProtoMsg(message: _75.ResponseEcho): _75.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            encode(_: _75.ResponseFlush, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.ResponseFlush;
            fromPartial(_: Partial<_75.ResponseFlush>): _75.ResponseFlush;
            fromAmino(_: _75.ResponseFlushAmino): _75.ResponseFlush;
            toAmino(_: _75.ResponseFlush): _75.ResponseFlushAmino;
            fromAminoMsg(object: _75.ResponseFlushAminoMsg): _75.ResponseFlush;
            fromProtoMsg(message: _75.ResponseFlushProtoMsg): _75.ResponseFlush;
            toProto(message: _75.ResponseFlush): Uint8Array;
            toProtoMsg(message: _75.ResponseFlush): _75.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            encode(message: _75.ResponseInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.ResponseInfo;
            fromPartial(object: Partial<_75.ResponseInfo>): _75.ResponseInfo;
            fromAmino(object: _75.ResponseInfoAmino): _75.ResponseInfo;
            toAmino(message: _75.ResponseInfo): _75.ResponseInfoAmino;
            fromAminoMsg(object: _75.ResponseInfoAminoMsg): _75.ResponseInfo;
            fromProtoMsg(message: _75.ResponseInfoProtoMsg): _75.ResponseInfo;
            toProto(message: _75.ResponseInfo): Uint8Array;
            toProtoMsg(message: _75.ResponseInfo): _75.ResponseInfoProtoMsg;
        };
        ResponseSetOption: {
            encode(message: _75.ResponseSetOption, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.ResponseSetOption;
            fromPartial(object: Partial<_75.ResponseSetOption>): _75.ResponseSetOption;
            fromAmino(object: _75.ResponseSetOptionAmino): _75.ResponseSetOption;
            toAmino(message: _75.ResponseSetOption): _75.ResponseSetOptionAmino;
            fromAminoMsg(object: _75.ResponseSetOptionAminoMsg): _75.ResponseSetOption;
            fromProtoMsg(message: _75.ResponseSetOptionProtoMsg): _75.ResponseSetOption;
            toProto(message: _75.ResponseSetOption): Uint8Array;
            toProtoMsg(message: _75.ResponseSetOption): _75.ResponseSetOptionProtoMsg;
        };
        ResponseInitChain: {
            encode(message: _75.ResponseInitChain, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.ResponseInitChain;
            fromPartial(object: Partial<_75.ResponseInitChain>): _75.ResponseInitChain;
            fromAmino(object: _75.ResponseInitChainAmino): _75.ResponseInitChain;
            toAmino(message: _75.ResponseInitChain): _75.ResponseInitChainAmino;
            fromAminoMsg(object: _75.ResponseInitChainAminoMsg): _75.ResponseInitChain;
            fromProtoMsg(message: _75.ResponseInitChainProtoMsg): _75.ResponseInitChain;
            toProto(message: _75.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _75.ResponseInitChain): _75.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            encode(message: _75.ResponseQuery, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.ResponseQuery;
            fromPartial(object: Partial<_75.ResponseQuery>): _75.ResponseQuery;
            fromAmino(object: _75.ResponseQueryAmino): _75.ResponseQuery;
            toAmino(message: _75.ResponseQuery): _75.ResponseQueryAmino;
            fromAminoMsg(object: _75.ResponseQueryAminoMsg): _75.ResponseQuery;
            fromProtoMsg(message: _75.ResponseQueryProtoMsg): _75.ResponseQuery;
            toProto(message: _75.ResponseQuery): Uint8Array;
            toProtoMsg(message: _75.ResponseQuery): _75.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            encode(message: _75.ResponseBeginBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.ResponseBeginBlock;
            fromPartial(object: Partial<_75.ResponseBeginBlock>): _75.ResponseBeginBlock;
            fromAmino(object: _75.ResponseBeginBlockAmino): _75.ResponseBeginBlock;
            toAmino(message: _75.ResponseBeginBlock): _75.ResponseBeginBlockAmino;
            fromAminoMsg(object: _75.ResponseBeginBlockAminoMsg): _75.ResponseBeginBlock;
            fromProtoMsg(message: _75.ResponseBeginBlockProtoMsg): _75.ResponseBeginBlock;
            toProto(message: _75.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _75.ResponseBeginBlock): _75.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            encode(message: _75.ResponseCheckTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.ResponseCheckTx;
            fromPartial(object: Partial<_75.ResponseCheckTx>): _75.ResponseCheckTx;
            fromAmino(object: _75.ResponseCheckTxAmino): _75.ResponseCheckTx;
            toAmino(message: _75.ResponseCheckTx): _75.ResponseCheckTxAmino;
            fromAminoMsg(object: _75.ResponseCheckTxAminoMsg): _75.ResponseCheckTx;
            fromProtoMsg(message: _75.ResponseCheckTxProtoMsg): _75.ResponseCheckTx;
            toProto(message: _75.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _75.ResponseCheckTx): _75.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            encode(message: _75.ResponseDeliverTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.ResponseDeliverTx;
            fromPartial(object: Partial<_75.ResponseDeliverTx>): _75.ResponseDeliverTx;
            fromAmino(object: _75.ResponseDeliverTxAmino): _75.ResponseDeliverTx;
            toAmino(message: _75.ResponseDeliverTx): _75.ResponseDeliverTxAmino;
            fromAminoMsg(object: _75.ResponseDeliverTxAminoMsg): _75.ResponseDeliverTx;
            fromProtoMsg(message: _75.ResponseDeliverTxProtoMsg): _75.ResponseDeliverTx;
            toProto(message: _75.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _75.ResponseDeliverTx): _75.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            encode(message: _75.ResponseEndBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.ResponseEndBlock;
            fromPartial(object: Partial<_75.ResponseEndBlock>): _75.ResponseEndBlock;
            fromAmino(object: _75.ResponseEndBlockAmino): _75.ResponseEndBlock;
            toAmino(message: _75.ResponseEndBlock): _75.ResponseEndBlockAmino;
            fromAminoMsg(object: _75.ResponseEndBlockAminoMsg): _75.ResponseEndBlock;
            fromProtoMsg(message: _75.ResponseEndBlockProtoMsg): _75.ResponseEndBlock;
            toProto(message: _75.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _75.ResponseEndBlock): _75.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            encode(message: _75.ResponseCommit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.ResponseCommit;
            fromPartial(object: Partial<_75.ResponseCommit>): _75.ResponseCommit;
            fromAmino(object: _75.ResponseCommitAmino): _75.ResponseCommit;
            toAmino(message: _75.ResponseCommit): _75.ResponseCommitAmino;
            fromAminoMsg(object: _75.ResponseCommitAminoMsg): _75.ResponseCommit;
            fromProtoMsg(message: _75.ResponseCommitProtoMsg): _75.ResponseCommit;
            toProto(message: _75.ResponseCommit): Uint8Array;
            toProtoMsg(message: _75.ResponseCommit): _75.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            encode(message: _75.ResponseListSnapshots, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.ResponseListSnapshots;
            fromPartial(object: Partial<_75.ResponseListSnapshots>): _75.ResponseListSnapshots;
            fromAmino(object: _75.ResponseListSnapshotsAmino): _75.ResponseListSnapshots;
            toAmino(message: _75.ResponseListSnapshots): _75.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _75.ResponseListSnapshotsAminoMsg): _75.ResponseListSnapshots;
            fromProtoMsg(message: _75.ResponseListSnapshotsProtoMsg): _75.ResponseListSnapshots;
            toProto(message: _75.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _75.ResponseListSnapshots): _75.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            encode(message: _75.ResponseOfferSnapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.ResponseOfferSnapshot;
            fromPartial(object: Partial<_75.ResponseOfferSnapshot>): _75.ResponseOfferSnapshot;
            fromAmino(object: _75.ResponseOfferSnapshotAmino): _75.ResponseOfferSnapshot;
            toAmino(message: _75.ResponseOfferSnapshot): _75.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _75.ResponseOfferSnapshotAminoMsg): _75.ResponseOfferSnapshot;
            fromProtoMsg(message: _75.ResponseOfferSnapshotProtoMsg): _75.ResponseOfferSnapshot;
            toProto(message: _75.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _75.ResponseOfferSnapshot): _75.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            encode(message: _75.ResponseLoadSnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.ResponseLoadSnapshotChunk;
            fromPartial(object: Partial<_75.ResponseLoadSnapshotChunk>): _75.ResponseLoadSnapshotChunk;
            fromAmino(object: _75.ResponseLoadSnapshotChunkAmino): _75.ResponseLoadSnapshotChunk;
            toAmino(message: _75.ResponseLoadSnapshotChunk): _75.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _75.ResponseLoadSnapshotChunkAminoMsg): _75.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _75.ResponseLoadSnapshotChunkProtoMsg): _75.ResponseLoadSnapshotChunk;
            toProto(message: _75.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _75.ResponseLoadSnapshotChunk): _75.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            encode(message: _75.ResponseApplySnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.ResponseApplySnapshotChunk;
            fromPartial(object: Partial<_75.ResponseApplySnapshotChunk>): _75.ResponseApplySnapshotChunk;
            fromAmino(object: _75.ResponseApplySnapshotChunkAmino): _75.ResponseApplySnapshotChunk;
            toAmino(message: _75.ResponseApplySnapshotChunk): _75.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _75.ResponseApplySnapshotChunkAminoMsg): _75.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _75.ResponseApplySnapshotChunkProtoMsg): _75.ResponseApplySnapshotChunk;
            toProto(message: _75.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _75.ResponseApplySnapshotChunk): _75.ResponseApplySnapshotChunkProtoMsg;
        };
        ConsensusParams: {
            encode(message: _75.ConsensusParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.ConsensusParams;
            fromPartial(object: Partial<_75.ConsensusParams>): _75.ConsensusParams;
            fromAmino(object: _75.ConsensusParamsAmino): _75.ConsensusParams;
            toAmino(message: _75.ConsensusParams): _75.ConsensusParamsAmino;
            fromAminoMsg(object: _75.ConsensusParamsAminoMsg): _75.ConsensusParams;
            fromProtoMsg(message: _75.ConsensusParamsProtoMsg): _75.ConsensusParams;
            toProto(message: _75.ConsensusParams): Uint8Array;
            toProtoMsg(message: _75.ConsensusParams): _75.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            encode(message: _75.BlockParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.BlockParams;
            fromPartial(object: Partial<_75.BlockParams>): _75.BlockParams;
            fromAmino(object: _75.BlockParamsAmino): _75.BlockParams;
            toAmino(message: _75.BlockParams): _75.BlockParamsAmino;
            fromAminoMsg(object: _75.BlockParamsAminoMsg): _75.BlockParams;
            fromProtoMsg(message: _75.BlockParamsProtoMsg): _75.BlockParams;
            toProto(message: _75.BlockParams): Uint8Array;
            toProtoMsg(message: _75.BlockParams): _75.BlockParamsProtoMsg;
        };
        LastCommitInfo: {
            encode(message: _75.LastCommitInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.LastCommitInfo;
            fromPartial(object: Partial<_75.LastCommitInfo>): _75.LastCommitInfo;
            fromAmino(object: _75.LastCommitInfoAmino): _75.LastCommitInfo;
            toAmino(message: _75.LastCommitInfo): _75.LastCommitInfoAmino;
            fromAminoMsg(object: _75.LastCommitInfoAminoMsg): _75.LastCommitInfo;
            fromProtoMsg(message: _75.LastCommitInfoProtoMsg): _75.LastCommitInfo;
            toProto(message: _75.LastCommitInfo): Uint8Array;
            toProtoMsg(message: _75.LastCommitInfo): _75.LastCommitInfoProtoMsg;
        };
        Event: {
            encode(message: _75.Event, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.Event;
            fromPartial(object: Partial<_75.Event>): _75.Event;
            fromAmino(object: _75.EventAmino): _75.Event;
            toAmino(message: _75.Event): _75.EventAmino;
            fromAminoMsg(object: _75.EventAminoMsg): _75.Event;
            fromProtoMsg(message: _75.EventProtoMsg): _75.Event;
            toProto(message: _75.Event): Uint8Array;
            toProtoMsg(message: _75.Event): _75.EventProtoMsg;
        };
        EventAttribute: {
            encode(message: _75.EventAttribute, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.EventAttribute;
            fromPartial(object: Partial<_75.EventAttribute>): _75.EventAttribute;
            fromAmino(object: _75.EventAttributeAmino): _75.EventAttribute;
            toAmino(message: _75.EventAttribute): _75.EventAttributeAmino;
            fromAminoMsg(object: _75.EventAttributeAminoMsg): _75.EventAttribute;
            fromProtoMsg(message: _75.EventAttributeProtoMsg): _75.EventAttribute;
            toProto(message: _75.EventAttribute): Uint8Array;
            toProtoMsg(message: _75.EventAttribute): _75.EventAttributeProtoMsg;
        };
        TxResult: {
            encode(message: _75.TxResult, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.TxResult;
            fromPartial(object: Partial<_75.TxResult>): _75.TxResult;
            fromAmino(object: _75.TxResultAmino): _75.TxResult;
            toAmino(message: _75.TxResult): _75.TxResultAmino;
            fromAminoMsg(object: _75.TxResultAminoMsg): _75.TxResult;
            fromProtoMsg(message: _75.TxResultProtoMsg): _75.TxResult;
            toProto(message: _75.TxResult): Uint8Array;
            toProtoMsg(message: _75.TxResult): _75.TxResultProtoMsg;
        };
        Validator: {
            encode(message: _75.Validator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.Validator;
            fromPartial(object: Partial<_75.Validator>): _75.Validator;
            fromAmino(object: _75.ValidatorAmino): _75.Validator;
            toAmino(message: _75.Validator): _75.ValidatorAmino;
            fromAminoMsg(object: _75.ValidatorAminoMsg): _75.Validator;
            fromProtoMsg(message: _75.ValidatorProtoMsg): _75.Validator;
            toProto(message: _75.Validator): Uint8Array;
            toProtoMsg(message: _75.Validator): _75.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            encode(message: _75.ValidatorUpdate, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.ValidatorUpdate;
            fromPartial(object: Partial<_75.ValidatorUpdate>): _75.ValidatorUpdate;
            fromAmino(object: _75.ValidatorUpdateAmino): _75.ValidatorUpdate;
            toAmino(message: _75.ValidatorUpdate): _75.ValidatorUpdateAmino;
            fromAminoMsg(object: _75.ValidatorUpdateAminoMsg): _75.ValidatorUpdate;
            fromProtoMsg(message: _75.ValidatorUpdateProtoMsg): _75.ValidatorUpdate;
            toProto(message: _75.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _75.ValidatorUpdate): _75.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            encode(message: _75.VoteInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.VoteInfo;
            fromPartial(object: Partial<_75.VoteInfo>): _75.VoteInfo;
            fromAmino(object: _75.VoteInfoAmino): _75.VoteInfo;
            toAmino(message: _75.VoteInfo): _75.VoteInfoAmino;
            fromAminoMsg(object: _75.VoteInfoAminoMsg): _75.VoteInfo;
            fromProtoMsg(message: _75.VoteInfoProtoMsg): _75.VoteInfo;
            toProto(message: _75.VoteInfo): Uint8Array;
            toProtoMsg(message: _75.VoteInfo): _75.VoteInfoProtoMsg;
        };
        Evidence: {
            encode(message: _75.Evidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.Evidence;
            fromPartial(object: Partial<_75.Evidence>): _75.Evidence;
            fromAmino(object: _75.EvidenceAmino): _75.Evidence;
            toAmino(message: _75.Evidence): _75.EvidenceAmino;
            fromAminoMsg(object: _75.EvidenceAminoMsg): _75.Evidence;
            fromProtoMsg(message: _75.EvidenceProtoMsg): _75.Evidence;
            toProto(message: _75.Evidence): Uint8Array;
            toProtoMsg(message: _75.Evidence): _75.EvidenceProtoMsg;
        };
        Snapshot: {
            encode(message: _75.Snapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _75.Snapshot;
            fromPartial(object: Partial<_75.Snapshot>): _75.Snapshot;
            fromAmino(object: _75.SnapshotAmino): _75.Snapshot;
            toAmino(message: _75.Snapshot): _75.SnapshotAmino;
            fromAminoMsg(object: _75.SnapshotAminoMsg): _75.Snapshot;
            fromProtoMsg(message: _75.SnapshotProtoMsg): _75.Snapshot;
            toProto(message: _75.Snapshot): Uint8Array;
            toProtoMsg(message: _75.Snapshot): _75.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            encode(message: _77.Proof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _77.Proof;
            fromPartial(object: Partial<_77.Proof>): _77.Proof;
            fromAmino(object: _77.ProofAmino): _77.Proof;
            toAmino(message: _77.Proof): _77.ProofAmino;
            fromAminoMsg(object: _77.ProofAminoMsg): _77.Proof;
            fromProtoMsg(message: _77.ProofProtoMsg): _77.Proof;
            toProto(message: _77.Proof): Uint8Array;
            toProtoMsg(message: _77.Proof): _77.ProofProtoMsg;
        };
        ValueOp: {
            encode(message: _77.ValueOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _77.ValueOp;
            fromPartial(object: Partial<_77.ValueOp>): _77.ValueOp;
            fromAmino(object: _77.ValueOpAmino): _77.ValueOp;
            toAmino(message: _77.ValueOp): _77.ValueOpAmino;
            fromAminoMsg(object: _77.ValueOpAminoMsg): _77.ValueOp;
            fromProtoMsg(message: _77.ValueOpProtoMsg): _77.ValueOp;
            toProto(message: _77.ValueOp): Uint8Array;
            toProtoMsg(message: _77.ValueOp): _77.ValueOpProtoMsg;
        };
        DominoOp: {
            encode(message: _77.DominoOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _77.DominoOp;
            fromPartial(object: Partial<_77.DominoOp>): _77.DominoOp;
            fromAmino(object: _77.DominoOpAmino): _77.DominoOp;
            toAmino(message: _77.DominoOp): _77.DominoOpAmino;
            fromAminoMsg(object: _77.DominoOpAminoMsg): _77.DominoOp;
            fromProtoMsg(message: _77.DominoOpProtoMsg): _77.DominoOp;
            toProto(message: _77.DominoOp): Uint8Array;
            toProtoMsg(message: _77.DominoOp): _77.DominoOpProtoMsg;
        };
        ProofOp: {
            encode(message: _77.ProofOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _77.ProofOp;
            fromPartial(object: Partial<_77.ProofOp>): _77.ProofOp;
            fromAmino(object: _77.ProofOpAmino): _77.ProofOp;
            toAmino(message: _77.ProofOp): _77.ProofOpAmino;
            fromAminoMsg(object: _77.ProofOpAminoMsg): _77.ProofOp;
            fromProtoMsg(message: _77.ProofOpProtoMsg): _77.ProofOp;
            toProto(message: _77.ProofOp): Uint8Array;
            toProtoMsg(message: _77.ProofOp): _77.ProofOpProtoMsg;
        };
        ProofOps: {
            encode(message: _77.ProofOps, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _77.ProofOps;
            fromPartial(object: Partial<_77.ProofOps>): _77.ProofOps;
            fromAmino(object: _77.ProofOpsAmino): _77.ProofOps;
            toAmino(message: _77.ProofOps): _77.ProofOpsAmino;
            fromAminoMsg(object: _77.ProofOpsAminoMsg): _77.ProofOps;
            fromProtoMsg(message: _77.ProofOpsProtoMsg): _77.ProofOps;
            toProto(message: _77.ProofOps): Uint8Array;
            toProtoMsg(message: _77.ProofOps): _77.ProofOpsProtoMsg;
        };
        PublicKey: {
            encode(message: _76.PublicKey, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _76.PublicKey;
            fromPartial(object: Partial<_76.PublicKey>): _76.PublicKey;
            fromAmino(object: _76.PublicKeyAmino): _76.PublicKey;
            toAmino(message: _76.PublicKey): _76.PublicKeyAmino;
            fromAminoMsg(object: _76.PublicKeyAminoMsg): _76.PublicKey;
            fromProtoMsg(message: _76.PublicKeyProtoMsg): _76.PublicKey;
            toProto(message: _76.PublicKey): Uint8Array;
            toProtoMsg(message: _76.PublicKey): _76.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                encode(message: _78.BitArray, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
                decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _78.BitArray;
                fromPartial(object: Partial<_78.BitArray>): _78.BitArray;
                fromAmino(object: _78.BitArrayAmino): _78.BitArray;
                toAmino(message: _78.BitArray): _78.BitArrayAmino;
                fromAminoMsg(object: _78.BitArrayAminoMsg): _78.BitArray;
                fromProtoMsg(message: _78.BitArrayProtoMsg): _78.BitArray;
                toProto(message: _78.BitArray): Uint8Array;
                toProtoMsg(message: _78.BitArray): _78.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        ProtocolVersion: {
            encode(message: _79.ProtocolVersion, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _79.ProtocolVersion;
            fromPartial(object: Partial<_79.ProtocolVersion>): _79.ProtocolVersion;
            fromAmino(object: _79.ProtocolVersionAmino): _79.ProtocolVersion;
            toAmino(message: _79.ProtocolVersion): _79.ProtocolVersionAmino;
            fromAminoMsg(object: _79.ProtocolVersionAminoMsg): _79.ProtocolVersion;
            fromProtoMsg(message: _79.ProtocolVersionProtoMsg): _79.ProtocolVersion;
            toProto(message: _79.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _79.ProtocolVersion): _79.ProtocolVersionProtoMsg;
        };
        NodeInfo: {
            encode(message: _79.NodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _79.NodeInfo;
            fromPartial(object: Partial<_79.NodeInfo>): _79.NodeInfo;
            fromAmino(object: _79.NodeInfoAmino): _79.NodeInfo;
            toAmino(message: _79.NodeInfo): _79.NodeInfoAmino;
            fromAminoMsg(object: _79.NodeInfoAminoMsg): _79.NodeInfo;
            fromProtoMsg(message: _79.NodeInfoProtoMsg): _79.NodeInfo;
            toProto(message: _79.NodeInfo): Uint8Array;
            toProtoMsg(message: _79.NodeInfo): _79.NodeInfoProtoMsg;
        };
        NodeInfoOther: {
            encode(message: _79.NodeInfoOther, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _79.NodeInfoOther;
            fromPartial(object: Partial<_79.NodeInfoOther>): _79.NodeInfoOther;
            fromAmino(object: _79.NodeInfoOtherAmino): _79.NodeInfoOther;
            toAmino(message: _79.NodeInfoOther): _79.NodeInfoOtherAmino;
            fromAminoMsg(object: _79.NodeInfoOtherAminoMsg): _79.NodeInfoOther;
            fromProtoMsg(message: _79.NodeInfoOtherProtoMsg): _79.NodeInfoOther;
            toProto(message: _79.NodeInfoOther): Uint8Array;
            toProtoMsg(message: _79.NodeInfoOther): _79.NodeInfoOtherProtoMsg;
        };
        PeerInfo: {
            encode(message: _79.PeerInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _79.PeerInfo;
            fromPartial(object: Partial<_79.PeerInfo>): _79.PeerInfo;
            fromAmino(object: _79.PeerInfoAmino): _79.PeerInfo;
            toAmino(message: _79.PeerInfo): _79.PeerInfoAmino;
            fromAminoMsg(object: _79.PeerInfoAminoMsg): _79.PeerInfo;
            fromProtoMsg(message: _79.PeerInfoProtoMsg): _79.PeerInfo;
            toProto(message: _79.PeerInfo): Uint8Array;
            toProtoMsg(message: _79.PeerInfo): _79.PeerInfoProtoMsg;
        };
        PeerAddressInfo: {
            encode(message: _79.PeerAddressInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _79.PeerAddressInfo;
            fromPartial(object: Partial<_79.PeerAddressInfo>): _79.PeerAddressInfo;
            fromAmino(object: _79.PeerAddressInfoAmino): _79.PeerAddressInfo;
            toAmino(message: _79.PeerAddressInfo): _79.PeerAddressInfoAmino;
            fromAminoMsg(object: _79.PeerAddressInfoAminoMsg): _79.PeerAddressInfo;
            fromProtoMsg(message: _79.PeerAddressInfoProtoMsg): _79.PeerAddressInfo;
            toProto(message: _79.PeerAddressInfo): Uint8Array;
            toProtoMsg(message: _79.PeerAddressInfo): _79.PeerAddressInfoProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            encode(message: _84.ValidatorSet, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _84.ValidatorSet;
            fromPartial(object: Partial<_84.ValidatorSet>): _84.ValidatorSet;
            fromAmino(object: _84.ValidatorSetAmino): _84.ValidatorSet;
            toAmino(message: _84.ValidatorSet): _84.ValidatorSetAmino;
            fromAminoMsg(object: _84.ValidatorSetAminoMsg): _84.ValidatorSet;
            fromProtoMsg(message: _84.ValidatorSetProtoMsg): _84.ValidatorSet;
            toProto(message: _84.ValidatorSet): Uint8Array;
            toProtoMsg(message: _84.ValidatorSet): _84.ValidatorSetProtoMsg;
        };
        Validator: {
            encode(message: _84.Validator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _84.Validator;
            fromPartial(object: Partial<_84.Validator>): _84.Validator;
            fromAmino(object: _84.ValidatorAmino): _84.Validator;
            toAmino(message: _84.Validator): _84.ValidatorAmino;
            fromAminoMsg(object: _84.ValidatorAminoMsg): _84.Validator;
            fromProtoMsg(message: _84.ValidatorProtoMsg): _84.Validator;
            toProto(message: _84.Validator): Uint8Array;
            toProtoMsg(message: _84.Validator): _84.ValidatorProtoMsg;
        };
        SimpleValidator: {
            encode(message: _84.SimpleValidator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _84.SimpleValidator;
            fromPartial(object: Partial<_84.SimpleValidator>): _84.SimpleValidator;
            fromAmino(object: _84.SimpleValidatorAmino): _84.SimpleValidator;
            toAmino(message: _84.SimpleValidator): _84.SimpleValidatorAmino;
            fromAminoMsg(object: _84.SimpleValidatorAminoMsg): _84.SimpleValidator;
            fromProtoMsg(message: _84.SimpleValidatorProtoMsg): _84.SimpleValidator;
            toProto(message: _84.SimpleValidator): Uint8Array;
            toProtoMsg(message: _84.SimpleValidator): _84.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _83.BlockIDFlag;
        blockIDFlagToJSON(object: _83.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _83.SignedMsgType;
        signedMsgTypeToJSON(object: _83.SignedMsgType): string;
        BlockIDFlag: typeof _83.BlockIDFlag;
        BlockIDFlagSDKType: typeof _83.BlockIDFlag;
        BlockIDFlagAmino: typeof _83.BlockIDFlag;
        SignedMsgType: typeof _83.SignedMsgType;
        SignedMsgTypeSDKType: typeof _83.SignedMsgType;
        SignedMsgTypeAmino: typeof _83.SignedMsgType;
        PartSetHeader: {
            encode(message: _83.PartSetHeader, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _83.PartSetHeader;
            fromPartial(object: Partial<_83.PartSetHeader>): _83.PartSetHeader;
            fromAmino(object: _83.PartSetHeaderAmino): _83.PartSetHeader;
            toAmino(message: _83.PartSetHeader): _83.PartSetHeaderAmino;
            fromAminoMsg(object: _83.PartSetHeaderAminoMsg): _83.PartSetHeader;
            fromProtoMsg(message: _83.PartSetHeaderProtoMsg): _83.PartSetHeader;
            toProto(message: _83.PartSetHeader): Uint8Array;
            toProtoMsg(message: _83.PartSetHeader): _83.PartSetHeaderProtoMsg;
        };
        Part: {
            encode(message: _83.Part, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _83.Part;
            fromPartial(object: Partial<_83.Part>): _83.Part;
            fromAmino(object: _83.PartAmino): _83.Part;
            toAmino(message: _83.Part): _83.PartAmino;
            fromAminoMsg(object: _83.PartAminoMsg): _83.Part;
            fromProtoMsg(message: _83.PartProtoMsg): _83.Part;
            toProto(message: _83.Part): Uint8Array;
            toProtoMsg(message: _83.Part): _83.PartProtoMsg;
        };
        BlockID: {
            encode(message: _83.BlockID, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _83.BlockID;
            fromPartial(object: Partial<_83.BlockID>): _83.BlockID;
            fromAmino(object: _83.BlockIDAmino): _83.BlockID;
            toAmino(message: _83.BlockID): _83.BlockIDAmino;
            fromAminoMsg(object: _83.BlockIDAminoMsg): _83.BlockID;
            fromProtoMsg(message: _83.BlockIDProtoMsg): _83.BlockID;
            toProto(message: _83.BlockID): Uint8Array;
            toProtoMsg(message: _83.BlockID): _83.BlockIDProtoMsg;
        };
        Header: {
            encode(message: _83.Header, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _83.Header;
            fromPartial(object: Partial<_83.Header>): _83.Header;
            fromAmino(object: _83.HeaderAmino): _83.Header;
            toAmino(message: _83.Header): _83.HeaderAmino;
            fromAminoMsg(object: _83.HeaderAminoMsg): _83.Header;
            fromProtoMsg(message: _83.HeaderProtoMsg): _83.Header;
            toProto(message: _83.Header): Uint8Array;
            toProtoMsg(message: _83.Header): _83.HeaderProtoMsg;
        };
        Data: {
            encode(message: _83.Data, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _83.Data;
            fromPartial(object: Partial<_83.Data>): _83.Data;
            fromAmino(object: _83.DataAmino): _83.Data;
            toAmino(message: _83.Data): _83.DataAmino;
            fromAminoMsg(object: _83.DataAminoMsg): _83.Data;
            fromProtoMsg(message: _83.DataProtoMsg): _83.Data;
            toProto(message: _83.Data): Uint8Array;
            toProtoMsg(message: _83.Data): _83.DataProtoMsg;
        };
        Vote: {
            encode(message: _83.Vote, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _83.Vote;
            fromPartial(object: Partial<_83.Vote>): _83.Vote;
            fromAmino(object: _83.VoteAmino): _83.Vote;
            toAmino(message: _83.Vote): _83.VoteAmino;
            fromAminoMsg(object: _83.VoteAminoMsg): _83.Vote;
            fromProtoMsg(message: _83.VoteProtoMsg): _83.Vote;
            toProto(message: _83.Vote): Uint8Array;
            toProtoMsg(message: _83.Vote): _83.VoteProtoMsg;
        };
        Commit: {
            encode(message: _83.Commit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _83.Commit;
            fromPartial(object: Partial<_83.Commit>): _83.Commit;
            fromAmino(object: _83.CommitAmino): _83.Commit;
            toAmino(message: _83.Commit): _83.CommitAmino;
            fromAminoMsg(object: _83.CommitAminoMsg): _83.Commit;
            fromProtoMsg(message: _83.CommitProtoMsg): _83.Commit;
            toProto(message: _83.Commit): Uint8Array;
            toProtoMsg(message: _83.Commit): _83.CommitProtoMsg;
        };
        CommitSig: {
            encode(message: _83.CommitSig, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _83.CommitSig;
            fromPartial(object: Partial<_83.CommitSig>): _83.CommitSig;
            fromAmino(object: _83.CommitSigAmino): _83.CommitSig;
            toAmino(message: _83.CommitSig): _83.CommitSigAmino;
            fromAminoMsg(object: _83.CommitSigAminoMsg): _83.CommitSig;
            fromProtoMsg(message: _83.CommitSigProtoMsg): _83.CommitSig;
            toProto(message: _83.CommitSig): Uint8Array;
            toProtoMsg(message: _83.CommitSig): _83.CommitSigProtoMsg;
        };
        Proposal: {
            encode(message: _83.Proposal, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _83.Proposal;
            fromPartial(object: Partial<_83.Proposal>): _83.Proposal;
            fromAmino(object: _83.ProposalAmino): _83.Proposal;
            toAmino(message: _83.Proposal): _83.ProposalAmino;
            fromAminoMsg(object: _83.ProposalAminoMsg): _83.Proposal;
            fromProtoMsg(message: _83.ProposalProtoMsg): _83.Proposal;
            toProto(message: _83.Proposal): Uint8Array;
            toProtoMsg(message: _83.Proposal): _83.ProposalProtoMsg;
        };
        SignedHeader: {
            encode(message: _83.SignedHeader, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _83.SignedHeader;
            fromPartial(object: Partial<_83.SignedHeader>): _83.SignedHeader;
            fromAmino(object: _83.SignedHeaderAmino): _83.SignedHeader;
            toAmino(message: _83.SignedHeader): _83.SignedHeaderAmino;
            fromAminoMsg(object: _83.SignedHeaderAminoMsg): _83.SignedHeader;
            fromProtoMsg(message: _83.SignedHeaderProtoMsg): _83.SignedHeader;
            toProto(message: _83.SignedHeader): Uint8Array;
            toProtoMsg(message: _83.SignedHeader): _83.SignedHeaderProtoMsg;
        };
        LightBlock: {
            encode(message: _83.LightBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _83.LightBlock;
            fromPartial(object: Partial<_83.LightBlock>): _83.LightBlock;
            fromAmino(object: _83.LightBlockAmino): _83.LightBlock;
            toAmino(message: _83.LightBlock): _83.LightBlockAmino;
            fromAminoMsg(object: _83.LightBlockAminoMsg): _83.LightBlock;
            fromProtoMsg(message: _83.LightBlockProtoMsg): _83.LightBlock;
            toProto(message: _83.LightBlock): Uint8Array;
            toProtoMsg(message: _83.LightBlock): _83.LightBlockProtoMsg;
        };
        BlockMeta: {
            encode(message: _83.BlockMeta, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _83.BlockMeta;
            fromPartial(object: Partial<_83.BlockMeta>): _83.BlockMeta;
            fromAmino(object: _83.BlockMetaAmino): _83.BlockMeta;
            toAmino(message: _83.BlockMeta): _83.BlockMetaAmino;
            fromAminoMsg(object: _83.BlockMetaAminoMsg): _83.BlockMeta;
            fromProtoMsg(message: _83.BlockMetaProtoMsg): _83.BlockMeta;
            toProto(message: _83.BlockMeta): Uint8Array;
            toProtoMsg(message: _83.BlockMeta): _83.BlockMetaProtoMsg;
        };
        TxProof: {
            encode(message: _83.TxProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _83.TxProof;
            fromPartial(object: Partial<_83.TxProof>): _83.TxProof;
            fromAmino(object: _83.TxProofAmino): _83.TxProof;
            toAmino(message: _83.TxProof): _83.TxProofAmino;
            fromAminoMsg(object: _83.TxProofAminoMsg): _83.TxProof;
            fromProtoMsg(message: _83.TxProofProtoMsg): _83.TxProof;
            toProto(message: _83.TxProof): Uint8Array;
            toProtoMsg(message: _83.TxProof): _83.TxProofProtoMsg;
        };
        ConsensusParams: {
            encode(message: _82.ConsensusParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _82.ConsensusParams;
            fromPartial(object: Partial<_82.ConsensusParams>): _82.ConsensusParams;
            fromAmino(object: _82.ConsensusParamsAmino): _82.ConsensusParams;
            toAmino(message: _82.ConsensusParams): _82.ConsensusParamsAmino;
            fromAminoMsg(object: _82.ConsensusParamsAminoMsg): _82.ConsensusParams;
            fromProtoMsg(message: _82.ConsensusParamsProtoMsg): _82.ConsensusParams;
            toProto(message: _82.ConsensusParams): Uint8Array;
            toProtoMsg(message: _82.ConsensusParams): _82.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            encode(message: _82.BlockParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _82.BlockParams;
            fromPartial(object: Partial<_82.BlockParams>): _82.BlockParams;
            fromAmino(object: _82.BlockParamsAmino): _82.BlockParams;
            toAmino(message: _82.BlockParams): _82.BlockParamsAmino;
            fromAminoMsg(object: _82.BlockParamsAminoMsg): _82.BlockParams;
            fromProtoMsg(message: _82.BlockParamsProtoMsg): _82.BlockParams;
            toProto(message: _82.BlockParams): Uint8Array;
            toProtoMsg(message: _82.BlockParams): _82.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            encode(message: _82.EvidenceParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _82.EvidenceParams;
            fromPartial(object: Partial<_82.EvidenceParams>): _82.EvidenceParams;
            fromAmino(object: _82.EvidenceParamsAmino): _82.EvidenceParams;
            toAmino(message: _82.EvidenceParams): _82.EvidenceParamsAmino;
            fromAminoMsg(object: _82.EvidenceParamsAminoMsg): _82.EvidenceParams;
            fromProtoMsg(message: _82.EvidenceParamsProtoMsg): _82.EvidenceParams;
            toProto(message: _82.EvidenceParams): Uint8Array;
            toProtoMsg(message: _82.EvidenceParams): _82.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            encode(message: _82.ValidatorParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _82.ValidatorParams;
            fromPartial(object: Partial<_82.ValidatorParams>): _82.ValidatorParams;
            fromAmino(object: _82.ValidatorParamsAmino): _82.ValidatorParams;
            toAmino(message: _82.ValidatorParams): _82.ValidatorParamsAmino;
            fromAminoMsg(object: _82.ValidatorParamsAminoMsg): _82.ValidatorParams;
            fromProtoMsg(message: _82.ValidatorParamsProtoMsg): _82.ValidatorParams;
            toProto(message: _82.ValidatorParams): Uint8Array;
            toProtoMsg(message: _82.ValidatorParams): _82.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            encode(message: _82.VersionParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _82.VersionParams;
            fromPartial(object: Partial<_82.VersionParams>): _82.VersionParams;
            fromAmino(object: _82.VersionParamsAmino): _82.VersionParams;
            toAmino(message: _82.VersionParams): _82.VersionParamsAmino;
            fromAminoMsg(object: _82.VersionParamsAminoMsg): _82.VersionParams;
            fromProtoMsg(message: _82.VersionParamsProtoMsg): _82.VersionParams;
            toProto(message: _82.VersionParams): Uint8Array;
            toProtoMsg(message: _82.VersionParams): _82.VersionParamsProtoMsg;
        };
        HashedParams: {
            encode(message: _82.HashedParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _82.HashedParams;
            fromPartial(object: Partial<_82.HashedParams>): _82.HashedParams;
            fromAmino(object: _82.HashedParamsAmino): _82.HashedParams;
            toAmino(message: _82.HashedParams): _82.HashedParamsAmino;
            fromAminoMsg(object: _82.HashedParamsAminoMsg): _82.HashedParams;
            fromProtoMsg(message: _82.HashedParamsProtoMsg): _82.HashedParams;
            toProto(message: _82.HashedParams): Uint8Array;
            toProtoMsg(message: _82.HashedParams): _82.HashedParamsProtoMsg;
        };
        Evidence: {
            encode(message: _81.Evidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _81.Evidence;
            fromPartial(object: Partial<_81.Evidence>): _81.Evidence;
            fromAmino(object: _81.EvidenceAmino): _81.Evidence;
            toAmino(message: _81.Evidence): _81.EvidenceAmino;
            fromAminoMsg(object: _81.EvidenceAminoMsg): _81.Evidence;
            fromProtoMsg(message: _81.EvidenceProtoMsg): _81.Evidence;
            toProto(message: _81.Evidence): Uint8Array;
            toProtoMsg(message: _81.Evidence): _81.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            encode(message: _81.DuplicateVoteEvidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _81.DuplicateVoteEvidence;
            fromPartial(object: Partial<_81.DuplicateVoteEvidence>): _81.DuplicateVoteEvidence;
            fromAmino(object: _81.DuplicateVoteEvidenceAmino): _81.DuplicateVoteEvidence;
            toAmino(message: _81.DuplicateVoteEvidence): _81.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _81.DuplicateVoteEvidenceAminoMsg): _81.DuplicateVoteEvidence;
            fromProtoMsg(message: _81.DuplicateVoteEvidenceProtoMsg): _81.DuplicateVoteEvidence;
            toProto(message: _81.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _81.DuplicateVoteEvidence): _81.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            encode(message: _81.LightClientAttackEvidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _81.LightClientAttackEvidence;
            fromPartial(object: Partial<_81.LightClientAttackEvidence>): _81.LightClientAttackEvidence;
            fromAmino(object: _81.LightClientAttackEvidenceAmino): _81.LightClientAttackEvidence;
            toAmino(message: _81.LightClientAttackEvidence): _81.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _81.LightClientAttackEvidenceAminoMsg): _81.LightClientAttackEvidence;
            fromProtoMsg(message: _81.LightClientAttackEvidenceProtoMsg): _81.LightClientAttackEvidence;
            toProto(message: _81.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _81.LightClientAttackEvidence): _81.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            encode(message: _81.EvidenceList, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _81.EvidenceList;
            fromPartial(object: Partial<_81.EvidenceList>): _81.EvidenceList;
            fromAmino(object: _81.EvidenceListAmino): _81.EvidenceList;
            toAmino(message: _81.EvidenceList): _81.EvidenceListAmino;
            fromAminoMsg(object: _81.EvidenceListAminoMsg): _81.EvidenceList;
            fromProtoMsg(message: _81.EvidenceListProtoMsg): _81.EvidenceList;
            toProto(message: _81.EvidenceList): Uint8Array;
            toProtoMsg(message: _81.EvidenceList): _81.EvidenceListProtoMsg;
        };
        Block: {
            encode(message: _80.Block, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _80.Block;
            fromPartial(object: Partial<_80.Block>): _80.Block;
            fromAmino(object: _80.BlockAmino): _80.Block;
            toAmino(message: _80.Block): _80.BlockAmino;
            fromAminoMsg(object: _80.BlockAminoMsg): _80.Block;
            fromProtoMsg(message: _80.BlockProtoMsg): _80.Block;
            toProto(message: _80.Block): Uint8Array;
            toProtoMsg(message: _80.Block): _80.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            encode(message: _85.App, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _85.App;
            fromPartial(object: Partial<_85.App>): _85.App;
            fromAmino(object: _85.AppAmino): _85.App;
            toAmino(message: _85.App): _85.AppAmino;
            fromAminoMsg(object: _85.AppAminoMsg): _85.App;
            fromProtoMsg(message: _85.AppProtoMsg): _85.App;
            toProto(message: _85.App): Uint8Array;
            toProtoMsg(message: _85.App): _85.AppProtoMsg;
        };
        Consensus: {
            encode(message: _85.Consensus, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _85.Consensus;
            fromPartial(object: Partial<_85.Consensus>): _85.Consensus;
            fromAmino(object: _85.ConsensusAmino): _85.Consensus;
            toAmino(message: _85.Consensus): _85.ConsensusAmino;
            fromAminoMsg(object: _85.ConsensusAminoMsg): _85.Consensus;
            fromProtoMsg(message: _85.ConsensusProtoMsg): _85.Consensus;
            toProto(message: _85.Consensus): Uint8Array;
            toProtoMsg(message: _85.Consensus): _85.ConsensusProtoMsg;
        };
    };
}
